### ISSUE TITLE
make build fails

### ISSUE THREAD

**Issue by mwetter** [ibpsa/project1-boptest#1]
`make build` fails with
```
Step 16/17 : COPY doc/ testcase/doc/
COPY failed: stat /var/lib/docker/tmp/docker-builder948542279/doc: no such file or directory
make: *** [build] Error 1
```
because `doc` does not exist.

Work-around: Create a `doc/README.md` file so that there is something to copy.

**Comment by dhblum** [comment]
Thanks Michael.

Closed by https://github.com/ibpsa/project1-boptest/pull/2.
