### ISSUE TITLE
Add capability for browser access

### ISSUE THREAD

**Issue by dhblum** [ibpsa/project1-boptest#112]
This issue is to address a problem with accessing the API of the BOPTEST testcase from a browser (e.g. using javascript), which can be fixed by adding the Flask-Cors package (https://pypi.org/project/Flask-Cors/) to the REST API.  

@SenHuang19 is this correct?  Can you post the error you are getting?

**Comment by SenHuang19** [comment]
Yes, the error that was showing in the console of a web browser is:  

> Access to XMLHttpRequest at 'http://127.0.0.1:5000/step' from origin 'null' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource

At the server side, the following log showed up as well:

> "OPTIONS /step HTTP/1.1" 404 - 

To mitigate the problem, I suggest to add the following code #114  to the restapi.py

> cors = CORS(app, resources={r"*": {"origins": "*"}})

This will allow the request from certain origins to access the server (by default it allows request from any domain but developers can modify it based on their needs)

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/167.
