### ISSUE TITLE
Using Overwrite blocks in arrays

### ISSUE THREAD

**Issue by SenHuang19** [ibpsa/project1-boptest#116]
This issue is to address the error when using Overwrite blocks in arrays.
Consider the following example:

> model test_model
>  IBPSA.Controls.Continuous.SignalRanker sigRan(nin=3);
>  Modelica.Blocks.Sources.Sine sine(freqHz=1/86400);
>  Modelica.Blocks.Sources.Sine sine1(freqHz=1/36400);
>  Modelica.Blocks.Sources.Sine sine2(freqHz=1/56400);
>  IBPSA.Utilities.IO.SignalExchange.Overwrite overwrite[3];
>equation
>  connect(sine.y, sigRan.u[1]) ;
>  connect(sine1.y, sigRan.u[2]) ;
>  connect(sine2.y, sigRan.u[3]) ;
>  connect(sigRan.y, overwrite.u);
>end test_model;

When compiling it into fmu, the following error occurs:

> Modifiers of specific array elements are not allowed

**Comment by dhblum** [comment]
Closing as is duplicated by https://github.com/ibpsa/project1-boptest/issues/190, which has more discussion.
