### ISSUE TITLE
Some models can’t compile in BOPTEST Docker on Windows 10

### ISSUE THREAD

**Issue by SunJ2019** [ibpsa/project1-boptest#122]
We noticed some of models (as below) can’t be generated to fmu successfully in Windows 10 BOPTEST docker container. The models are attached in the file: testcase4.zip. These models used the building library of Version: 6.0.0, 2019-07-15. This issue didn’t occur in PC with Linux OS.  

Failed 
FRPMultiZone
FRPMultiZone_FF
FRPMultiZone_Second_Floor:
 
Succeeded 
FRPMultiZone_First_Floor
FRPSingleZone 
FRPSingleZone_FF 
FRPSingleZone_FF_Walls
FRPSingleZone_v2

The Error information is as below: 
Traceback (most recent call last):
  File "compile_fmu.py", line 27, in <module>
    fmu_path = compile_fmu(modelpath, mopath,compiler_log_level='error',target='me',version='2.0',jvm_args='-Xmx5g')
  File "/usr/local/JModelica/Python/pymodelica/compiler.py", line 146, in compile_fmu
    separate_process, jvm_args)
  File "/usr/local/JModelica/Python/pymodelica/compiler.py", line 255, in _compile_unit
    compiler_options, compile_to, compiler_log_level, jvm_args)
  File "/usr/local/JModelica/Python/pymodelica/compiler.py", line 371, in compile_separate_process
    return log.end();
  File "/usr/local/JModelica/Python/pymodelica/compiler_logging.py", line 329, in end
    raise IOError(exception.message)
IOError: Unexpected end of output from the compiler:
...
</Warning>

Dump of the log has been saved in /tmp/JM_LOG_DUMP_Ig32tT

[testcase4.zip](https://github.com/ibpsa/project1-boptest/files/3809851/testcase4.zip)

**Comment by dhblum** [comment]
@mwetter Have you ever seen problems compiling a model with your JModelica docker running on a Windows 10 OS?

**Comment by dhblum** [comment]
@SunJ2019 Have you tried (successfully?) to compile the same models that are failing with JModelica installed natively on your Windows 10 OS?

**Comment by dhblum** [comment]
@SunJ2019 In testing the compilation of your models on a Linux VM, it seems the ones that you report to fail require more memory to compile than the ones that successfully compile.  Can you report the memory availability of the machines with Linux OS and Windows 10 OS?  Perhaps try monitoring the memory consumption of the compilations on your Windows machine and see if there are issues there.

**Comment by mwetter** [comment]
@dhblum : I have not heard from users about problems compiling models with the docker image on Windows 10.

**Comment by SunJ2019** [comment]
@dhblum seem the Windows machine has enough memory availability, attached is the memory consumption log.

[System Monitor Log.zip](https://github.com/ibpsa/project1-boptest/files/3865417/System.Monitor.Log.zip)

**Comment by dhblum** [comment]
@SunJ2019 I cannot open the .blg file on my mac or linux.  I don't currently have a Windows system available.  Can you convert to csv or other data file?

**Comment by SunJ2019** [comment]
@dhblum not sure how to convert the .blg file to csv file, attached is the screen shot of the memory usage plot. also I'm attaching the docker complier logging file.

[MemoryUsage.docx](https://github.com/ibpsa/project1-boptest/files/3918495/MemoryUsage.docx)
[compiler_logging.zip](https://github.com/ibpsa/project1-boptest/files/3918501/compiler_logging.zip)

**Comment by dhblum** [comment]
@SunJ2019 Are you able to compile the models with a native installation of JModelica on your Windows machine?  That is, not with the Docker container.

**Comment by ybae0330** [comment]
I have tried and there are some additional issues to be resolved before comparing two different environment. Here are the issues, files, and error messages.
[Issue Report.zip](https://github.com/ibpsa/project1-boptest/files/3928638/Issue.Report.zip)

**Comment by SenHuang19** [comment]
I installed Docker in Window 10 and sucessfully compiled the two models in the "issue Report.zip" after fixing class path of some modules. I suggest to close this issue.

**Comment by dhblum** [comment]
Thanks Sen and Yeonjin.  Closing since this issue is not directly related to BOPTEST.
