### ISSUE TITLE
Reduce memory requirements when loading results

### ISSUE THREAD

**Issue by dhblum** [ibpsa/project1-boptest#124]
Even for a single-zone test case, the result file output by JModelica for a year-long simulation using cvode and default communication step settings can be very large.  This can potentially trigger memory errors, particularly if the whole year is simulated at one time, when loading results for KPI calculation or reporting result trajectories to the user through the BOPTEST API calls ``/results``and ``/kpi``.  A few suggested solutions to add to ``testcase.py``:

1. Use the option ``['ncp']`` to set a constant result reporting timestep that is generally larger than the step size(s) of the solver.
2. Use the option ``['CVode_options']['store_event_points'] = False`` to prevent storing event points.  In a test, this reduced the a result file by ~3x (both results were already using 1.). 
3. Use the option ``['filter']`` to set which variables to store in the results file.  In a test that stored only test case FMU inputs and outputs, this alone reduced the result file by ~50x.  

Noting that the BOPTEST API calls ``/results`` and ``/kpi`` each only use data from test case FMU inputs and outputs, methods 3. and 2. are my preferred initial approaches to reducing memory requirements.  These methods prove to be very effective and this also maintains flexibility in the communication points.

**Comment by dhblum** [comment]
@SenHuang19 This may interest you, as you've reported issues in the past.

**Comment by dhblum** [comment]
An additional note on this issue.  The result file generated by pyfmi depends on a combination of model size (number of variables) and simulation step length.  The issue can be somewhat mitigated by BOPTEST since we only save variables of interest between simulation steps, so if these steps are not too long, the result file size generated by pyfmi may not be an issue.  But it could be tougher to tell for very large models at what simulation step length it may become an issue.

**Comment by SenHuang19** [comment]
I suggest 
-  we add a try block  to the advance API so that we could provide debug information rather than just showing the error message from Jmodelica
-  we add a new API to allow users to select the simulation modes: 
                 Default mode:  all the three settings (ncp, store_event_points, and filter) are implemented 
                 Debug mode:  no customized settings
-  besides the three settings, we could use "result_handling" to store data to a file (disk)

I have some initial code ready for implementing the above items

**Comment by dhblum** [comment]
Closing via https://github.com/ibpsa/project1-boptest/issues/240 and as stale.
