### ISSUE TITLE
Signal overwrite/send block that does not require a socket connection

### ISSUE THREAD

**Issue by mwetter** [ibpsa/project1-boptest#15]
This issue is to develop and review a signal overwrite block and send block that does not require a socket connection. Rather, the approach is to parse a model with modelica-json, and generate a model that instantiates the original model and exposes the signal as inputs (for the overwrite blocks) and outputs (for the read blocks).

Advantages are
- Users can simulate the FMU with any tool that can simulate FMUs.
- No socket connection is needed to communicate with the FMU.
- Users do not need to manually expose the inputs/output. Rather they instantiate as before the two blocks.
- BOPTEST can be used with any FMU, also non-Modelica.
- All the API is based on the FMI standard, rather than us having to define what exchanging signals through the socket means semantically.

Disadvantages are
- Unless the top-level Modelica model that will be exported as an FMU is hand-written, modelica-json needs to be used together with a code generator that reads the modelica-json output and generates the top-level modelica model.
- The number of inputs and outputs of the FMU will be large (two times the number of inputs, plus the number of outputs). However, inputs can be disabled through a boolean input signal if they are not needed.

**Comment by dhblum** [comment]
To point 1 of disadvantages, modelica-json was planned to be used also for KPI tagging within the model.

**Comment by mwetter** [comment]
Added example code to branch `issue15_signalOverwriteNoSocket`. (The code generation is not yet implemented. For this small example, the top-level model was written manually.)

**Comment by SenHuang19** [comment]
Is it possible to combine the ones w/ socket and the one w/o socket connection together?

**Comment by mwetter** [comment]
What do you mean by combine together?
The main point of the new design is to not having to use a socket in order
to make the use and the software testing simpler.

**Comment by SenHuang19** [comment]
I mean 
1. we add one Type to the overwriting/reading block to allow user to select whether the socket client is needed or not;
2. we also add inner/outer structure to allow the output/input of the overwriting/reading block to be exported to the upper level.

**Comment by dhblum** [comment]
Instead of modelica-json, ``parser/parser.py`` was written to identify locations of overwrite blocks, write the Modelica wrapper, and export as new FMU.  This method has been tested and implemented in testcase1 and testcase2.  The package containing the blocks is located in ``parser/SignalExchange.mo``.  @mwetter should the Modelica package be moved to the IBPSA Library?  What about parser/parser.py?

**Comment by mwetter** [comment]
@dhblum The signal exchange blocks should be in the IBPSA library so that model builder can easily access them through the respective libraries.
I suggest to keep `parser.py` in the BOPTEST repository.
