### ISSUE TITLE
TestCase: BESTEST hydronic

### ISSUE THREAD

**Issue by JavierArroyoBastida** [ibpsa/project1-boptest#159]
This issue is to create the single-zone residential hydronic test-case. The model itself is being developed in https://github.com/open-ideas/IDEAS/issues/996. This issue is to extend such model, add the test case data and compile the model.

**Comment by JavierArroyoBastida** [comment]
This is being addressed in https://github.com/JavierArroyoBastida/project1-boptest/tree/issue159_testcaseBestestHydronic. 
The model exteds from an example in the IDEAS Modelica library. Hence, do not close this issue at least until https://github.com/open-ideas/IDEAS/issues/996 is closed.

**Comment by dhblum** [comment]
@JavierArroyoBastida I have created the development branch on this repo issue159_testcaseBestestHydronic (https://github.com/ibpsa/project1-boptest/tree/issue159_testcaseBestestHydronic).  Can you please make a PR against this branch from your fork, so that we may begin the merge to the master.

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/219.
