### ISSUE TITLE
Set forecast default parameters

### ISSUE THREAD

**Issue by JavierArroyoBastida** [ibpsa/project1-boptest#165]
This is to set the forecast default parameters when calling the `forecaster.get_forecast()` method directly. When using the testcase API the 'horizon' and 'interval' parameters are properly set, however, this does not happen if calling the method directly. In that case, nothing prevents the forecaster from passing interval=None, in this line: 

https://github.com/ibpsa/project1-boptest/blob/132b83282e4c3c4e3ff229187f97a5899f28eaf0/forecast/forecaster.py#L65

which eventually leads to the use of the case control step for interpolation in the data manager:

https://github.com/ibpsa/project1-boptest/blob/132b83282e4c3c4e3ff229187f97a5899f28eaf0/data/data_manager.py#L212

Calling the forecaster directly can happen, for instance, for unit-testing. So far it has not been an issue because the unit tests of the forecast are implemented for testcase2 which uses the same period for the control step than for the forecaster interval.

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/166.
