### ISSUE TITLE
Example Julia controller

### ISSUE THREAD

**Issue by dhblum** [ibpsa/project1-boptest#17]
This issue is to implement an example controller that performs the same tasks as ``examples/twoday-p.py`` and ``examples/szvav-sup.py`` in testing with testcase1 and testcase2.

To Do:
- [x] Initial implementation
- [x] Add unit test.
- [x] Arrange directory structure in examples to make clear distinction between Julia examples and Python examples.
- [x] Fix sleep issue
- [x] Replace docker compose with make file.

**Comment by SenHuang19** [comment]
1. a new branch is created for this issue;
2. initial implementation is pushed;
3. A docker compose structure is added, let me know if we want to use the docker compose to replace the current make files

**Comment by dhblum** [comment]
The following is still needed: 
[] Add unit test.
[] Arrange directory structure in examples to make clear distinction between Julia examples and Python examples.

**Comment by dhblum** [comment]
Sleep issue addressed in https://github.com/ibpsa/project1-boptest/pull/56.

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/69.
