### ISSUE TITLE
Specify customized kpi results

### ISSUE THREAD

**Issue by dhblum** [ibpsa/project1-boptest#170]
When running examples in ``examples/python`` with customized kpis, it would be good to specify in the print statements that they are printing customized kpis, instead of core kpis, so as not to cause confusion.

**Comment by SenHuang19** [comment]
or should we add a API to export those customized kpis?

**Comment by dhblum** [comment]
Do you mean adding an API call to ``restapi.py``?  That would require making the customized kpi calculation internal to the BOPTEST testcase when deployed.  Right now, it is external.

**Comment by SenHuang19** [comment]
Thanks for your clarification. What I tried to say is that we can potentially move the KPI calculation into the server side., say let users to send the calculation config (json format) to the server with post and server will calculate this accordingly and return the results to users. 
In addition, regarding the print statement, do you think we should use logging library? That way we could enable logging level.

**Comment by dhblum** [comment]
I agree about the logging.

I see what you're saying about sending the customized kpi calc json configuration into the server.  It is an interesting idea and something that would be good to move internally, with an optional API call(s) to setup.

Perhaps this issue should address the logging and a new issue should be raised to move the custom kpi calc internally.

**Comment by dhblum** [comment]
Closing this issue as stale.  Separate printing of customized KPIs in the results is now done, i.e. via https://github.com/ibpsa/project1-boptest/blob/master/examples/python/interface.py#L206, which was added by https://github.com/ibpsa/project1-boptest/issues/692.
