### ISSUE TITLE
Overwrite block also output measurement by default

### ISSUE THREAD

**Issue by dhblum** [ibpsa/project1-boptest#193]
This issue is to discuss whether the overwrite block should also output a measurement by default, so as not to have to separately add overwrite and read blocks, for instance for reading setpoints within the model.

**Comment by JavierArroyoBastida** [comment]
I support this motion as it's very useful for system identification. Otherwise we'll end up adding a read block after almost every overwrite block in the models. Maybe there could be an optional parameter in the overwrite block defining whether a measurement should be retrieved from it or not.

**Comment by dhblum** [comment]
Good idea with the optional parameter.  I know @SenHuang19 supports this as well.

**Comment by dhblum** [comment]
Closed via https://github.com/ibpsa/project1-boptest/issues/364.
