### ISSUE TITLE
Unit tests for bestest hydronic

### ISSUE THREAD

**Issue by JavierArroyoBastida** [ibpsa/project1-boptest#220]
@dhblum looks like I didn't add the `make test_bestest_hydronic` to the `make test_all` call... so tests for that testcase are still not triggered in Travis. It's a small edit and was running the tests locally before the merge to the master, so shouldn't be an issue. I just suspect there could still pop up permission errors for the file `set_library_versions.sh` of that model. If tests don't pass for that reason, I suggest you directly overwrite that file.

**Comment by JavierArroyoBastida** [comment]
Tests pass so should be directly ready to merge (no need to overwrite `set_library_versions.sh` file.

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/221.
