### ISSUE TITLE
Set library versions json

### ISSUE THREAD

**Issue by JavierArroyoBastida** [ibpsa/project1-boptest#222]
This issue is to avoid the use of `set_library_versions.sh` as permission errors arise when these files are not originally generated in a Linux machine (independently of their content). See for instance:

https://travis-ci.com/github/ibpsa/project1-boptest/builds/176472241 
or
https://travis-ci.com/github/ibpsa/project1-boptest/builds/176475619 

An alternative may be to store the versions in a json file and checkout the libraries from a python script that reads such file.

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/223.
