### ISSUE TITLE
Initialize return

### ISSUE THREAD

**Issue by JavierArroyoBastida** [ibpsa/project1-boptest#224]
@dhblum, @SenHuang19, is there a reason why `testcase.initialize()` is returning a boolean? see: https://github.com/ibpsa/project1-boptest/blob/042ef3965f6c9ea18e2ce7bd69901cabdc69d572/testcase.py#L239
From personal use I'd find much more useful that it returns the same format as a regular `testcase.advance()` call to use it as an initial measurement for starting up the control algorithms. What do you think? if you agree I can work on that.

**Comment by dhblum** [comment]
I think that's a nice catch and sounds good.

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/225.
