### ISSUE TITLE
graphql API for Forecast

### ISSUE THREAD

**Issue by dhblum** [ibpsa/project1-boptest#226]
@kbenne From the documentation provided on the right side of the screen when browsing at localhost/graphql, it is unclear if there is a way to get the forecast data from the test case.

Mutations:
<img width="1852" alt="Screen Shot 2020-07-29 at 3 38 01 PM" src="https://user-images.githubusercontent.com/19480999/88845140-b982e000-d1b1-11ea-8369-acd7bfc9a696.png">

Query:
<img width="1854" alt="Screen Shot 2020-07-29 at 3 39 57 PM" src="https://user-images.githubusercontent.com/19480999/88845205-ce5f7380-d1b1-11ea-9511-1d34eb154f0e.png">

**Comment by dhblum** [comment]
The PR https://github.com/ibpsa/project1-boptest/pull/252 can address this issue since it adds the forecast API to the rest API.  The user does not need to go through graphql in this case.

**Comment by kbenne** [comment]
graphql is no more. just the same rest API that is implemented on master. closing.
