### ISSUE TITLE
Use commits to set versions

### ISSUE THREAD

**Issue by JavierArroyoBastida** [ibpsa/project1-boptest#232]
@dhblum, some testcases use branch names instead of commits to set library versions of required dependencies. This practice is dangerous as branches are dynamic and can thus introduce new erros into the models. An example is what has happened in [this build](https://github.com/ibpsa/project1-boptest/runs/1062946080). I propose to always checkout commits of the dependency libraries and to perform manual (and thus controlled) updates when required.

**Comment by dhblum** [comment]
I agree with this.

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/233.
