### ISSUE TITLE
Add weather measurements

### ISSUE THREAD

**Issue by dhblum** [ibpsa/project1-boptest#234]
Weather data should be added to the emulator model measurement signals, simulating weather stations that may be located at building sites.  Otherwise, in order to get historic weather data, a user needs to keep track of forecasts, which is not intuitive and not sustainable if in the future forecasts are not deterministic.

I will prototype with the bestest air test case.  Weather measurements could be added to each emulator individually, or perhaps a "weather station" block can be added to the IBPSA Modelica Library which takes as input a weather bus and already includes a standard set of signal exchange block mapping to weather measurements.

**Comment by dhblum** [comment]
Weather station prototyped in https://github.com/ibpsa/project1-boptest/tree/issue234_addWeaSta

**Comment by JavierArroyoBastida** [comment]
@dhblum I'm not sure this is a necessary feature. Actually one could argue that having a weather station in each building is less realistic than retrieving the weather data from weather forecast services which usually also provide current weather conditions for every location (see [this one](https://openweathermap.org/api/one-call-api?gclid=CjwKCAjw74b7BRA_EiwAF8yHFGU2UTllhGlbMXui4_xTF39XYJI-cJZrDAwq_eqqy8dq-NZzJxcruhoC7ZIQAvD_BwE) for instance). If we include stochastic forecast in the future, the emulator error should be dependent on the prediction horizon, with very low to none error for prediction horizons of 0 (current time).

**Comment by dhblum** [comment]
@JavierArroyoBastida So you are saying it should be up to the user to query and store forecasts in order to collect a record of weather "measurements", where the "measurement" is the forecast for prediction horizon of 0, which may also have error compared to the values used in the Modelica model for an actual simulation step?  This is rather than a record of measured historic weather used in the Modelica model be available in the results data structure, similar to something like zone temperatures or HVAC equipment power measurement data?

**Comment by JavierArroyoBastida** [comment]
I'm trying to think how I would do in reality to gather weather data for a location where a weather station is not available, and it would be like that: I would call a weather API service asking for the weather of that location every sampling time. The differences between the provided values and the values used in the Modelica model should not be larger than the typical errors associated to provide weather data using a weather API service for a specific location. Therefore, I would indeed have to talk on the one hand with the BMS to gather historical zone temperatures and HVAC measurement data, and on the other hand with the weather API service to gather weather data.

I must say that I see the value in what you're proposing though. It's probably more intuitive to have weather data directly as measurements. Also For BMS buildings that integrate a weather station your solution aligns better with reality as well because in those cases I would not make use use of a separate weather service to retrieve that data but I'd use the BMS itself... so I guess it's a design choice and would understand if we go for it.

**Comment by dhblum** [comment]
I understand what you are saying about using a weather forecast API.  But, there are definitely a number of scenarios.  

1) A weather station is installed for a building and integrated in the BMS system and associated database.
2) A weather station is installed near the building site and the data is available through another service or database, separate from the BMS.  This could be, for instance, a building on a campus where the campus has a weather station (this is the setup of my ongoing demo in Berkeley), or it could be that a regional or national weather service has a weather station nearby and the historic data is accessible (e.g. WeatherUnderground, NOAA). 
3) There is no weather station anywhere close to the building and/or these measurements are not accessible.  Then, the historic measurements would have have to come from storing values from a forecasting service that estimates what the current conditions are, or from using the initial value of a forecast.

There could be a combination of the above too, where a BMS weather station may not have all of the measurements needed, and therefore other services are used for such measurements.

But for controller testing and development, at least having the ability in BOPTEST to test for cases 1) and 2) I think would be valuable.  I also know there could be error in the historic measurements due to sensor or the fact that the location of the measurement and site don't exactly align, but these are different errors than forecast error, and could again be treated separately.  But starting with the deterministic case(s) is a good starting point in my opinion.

**Comment by JavierArroyoBastida** [comment]
Fair enough. I agree that for controller testing and development it is reasonable (and even valuable) to consider scenarios 1) and 2). So let's go for it.

**Comment by dhblum** [comment]
@JavierArroyoBastida https://github.com/ibpsa/project1-boptest/pull/255 adds the weather station for ``bestest_air``.  Should it be added to the hydronic cases through BOPTEST repo or IDEAS?

**Comment by JavierArroyoBastida** [comment]
Indeed. The hydronic cases live as examples of the IDEAS library and avoid external dependencies. Therefore, implementing this would require the IDEAS library to merge the latest developments of IBPSA as the `IBPSA.Utilities.IO.SignalExchange.WeatherStation` model is needed for this change. @Mathadon is that something that can be done?

**Comment by Mathadon** [comment]
@JavierArroyoBastida yup, is it urgent?

**Comment by JavierArroyoBastida** [comment]
I'm not in a particular rush for this, so if @dhblum is not either then not urgent.

**Comment by dhblum** [comment]
For me, it doesn't have to be done tomorrow or anything.  But is it possible within the next few weeks or month or so?  As I and others start testing MPC controllers on the emulators this year, it'd be good to have this implemented earlier rather than later to help maintain consistency.

**Comment by Mathadon** [comment]
You can use the branch associated with https://github.com/open-ideas/IDEAS/pull/1180/

**Comment by JavierArroyoBastida** [comment]
Unit-tests in BOPTEST are checkig out the master branch of IDEAS, so using a different branch would require further (small) changes. @Mathadon do you expect long time to have it in master? if not, I'd better wait. If yes then I'll go with that IDEAS branch and shift once master is ready.

**Comment by Mathadon** [comment]
I don't expect it to take long. There are some hiccups with the unit test results though.

**Comment by JavierArroyoBastida** [comment]
Ok! I'll wait a bit then, please ping us when ready.

**Comment by Mathadon** [comment]
merged

**Comment by JavierArroyoBastida** [comment]
great, thanks!

**Comment by dhblum** [comment]
Great thanks @Mathadon! @JavierArroyoBastida Are you going to work on adding the station to the other models or you want me to?

**Comment by JavierArroyoBastida** [comment]
I may have the time to implement this by next week, would that work?

**Comment by dhblum** [comment]
Yea that would be no problem.

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/255.
