### ISSUE TITLE
compiling and Jmodelica

### ISSUE THREAD

**Issue by zephyr0722** [ibpsa/project1-boptest#235]
I am trying to change the parameter in SimpleRC.mo from testcases/testcase1/models, but when I tried to use "compile_fmu.py" to compile the model tu .fmu document, there are a lot of problems. And I have also tried to download and install Jmodelica, and now the website of Jmodelica is closed. I found a source and download Jmodelica.org.2-14, but there were also the problems:
EnvironmentError: The environment variable JMODELICA_HOME is not set or points to a non-existing location.

I found a guide to install Jmodelica but when I tried to compile and build Jmodelica.org, there were also lots of errors:
make[2]: Entering directory '/var/local/home/zguo/JModelica.org-2.14/build/sundials_build'
make[2]: *** No rule to make target 'install'.  Stop.
make[2]: Leaving directory '/var/local/home/zguo/JModelica.org-2.14/build/sundials_build'
make[1]: *** [Makefile:432: all-local] Error 2
make[1]: Leaving directory '/var/local/home/zguo/JModelica.org-2.14/build/ThirdParty/Sundials'
make: *** [Makefile:442: install-recursive] Error 1

Could you help me?
or could you give me some other suggestions to import and analyse the new models?

**Comment by JavierArroyoBastida** [comment]
Hey @zephyr0722, you don't need to install JModelica to use BOPTEST. We use JModelica within a docker image to compile the models. You can find the Dockerfile for that image [here](https://github.com/ibpsa/project1-boptest/blob/master/testing/Dockerfile). Additionally, [this makefile](https://github.com/ibpsa/project1-boptest/blob/master/testing/makefile) helps to run commands on building that image, compiling models... However, I am wondering in first place: why do you need to change parameters and compile testcase1? that test case is used for testing purposes. If you just want to run any of the BOPTEST test cases please read carefully the section **Run Prototype Test Cases** at the main page of BOPTEST. 
To analise the models you may want to go to the documentation folder of each test case like [this one](https://github.com/ibpsa/project1-boptest/tree/master/testcases/bestest_hydronic_heat_pump/doc). Or you can simply open the modelica models and go through them.

**Comment by zephyr0722** [comment]
Hey @JavierArroyoBastida. Thank you for your answer, I am not familiar with the project, and I just want to analyse my own modelica models, so I want to change the parameter from the testcase to see the difference between the results. 
I have seen the documentation folder that you have shown me, as what you have said, so should  I just make a new folder with the same structure like the folders in the testcase, for example, make a folder named "mytest"and put the modelica models and the corrected compile_fmu.py in models' folder?  And a question is: I have found, that only the wrapper.fmu would be copied into the container, so when I "make build" like it was shown at the main page of BOPTEST, could I get the wrapper.fmu, or should I compie the wrapper.mo to get the wrapper.fmu before "make build"? That is also why I tried to change the parameters from SimpleRC.

**Comment by JavierArroyoBastida** [comment]
So if I understand correctly, you want to analyze your Modelica models using the BOPTEST interface? Notice that BOPTEST is meant to plug external controllers to assess their performance. If you are just interested in the analysis of your Modelica models I don't think BOPTEST is the way to go. I'd rather use pyfmi which used to be a package of JModelica but it's still supported as a standalone open source project. Check their documentation [here](https://jmodelica.org/pyfmi/).

**Comment by zephyr0722** [comment]
I want to assess the performance of external controllers, too, but I thought, maybe I would have to face different models, so I tried to import my own models. So you mean, that I could analyse different controllers by using the models and testcases, which offerd by Boptest,right?

**Comment by JavierArroyoBastida** [comment]
Although it could be possible to add additional models, the models provided by BOPTEST are to be used as a standard benchmark so that all controller developers assess their controllers against the same reference models. I wouldn't recommend you to try to add your own test cases because you wouldn't be able to compare your results with those from others, and also because the process of adding new emulator models is not straightforward.

**Comment by dhblum** [comment]
The test cases are provided in BOPTEST for anyone to analyze different controllers on them.  To the question on developing a test case, ``wrapped.fmu`` needs to be compiled before ``make build`` is used.  It is done by calling the parser in ``compile_fmu.py`` on the Modelica model of interest.  The compilation requires the use of the JModelica docker container, which can be invoked as is demonstrated in the unit testing makefile (``testing/makefile``).

Are there further issues here to address or shall I close?

**Comment by dhblum** [comment]
Closing as stale.
