### ISSUE TITLE
FMU compatibility issue

### ISSUE THREAD

**Issue by SenHuang19** [ibpsa/project1-boptest#242]
when trying to run testcase 1 and 2, the following error occurs:

> FMIL: module = FMIZIP, log level = 1: Unpacking of FMU /home/developer/models/wrapped.fmu into /tmp/JModelica.org/jm_tmpbyfXrF failed
Traceback (most recent call last):
  File "restapi.py", line 27, in <module>
    case = TestCase()
  File "/home/developer/testcase.py", line 33, in __init__
    self.fmu = load_fmu(self.fmupath)
  File "src/pyfmi/fmi.pyx", line 8000, in pyfmi.fmi.load_fmu
pyfmi.fmi.FMUException: The FMU version could not be determined. Unpacking of FMU /home/developer/models/wrapped.fmu into /tmp/JModelica.org/jm_tmpbyfXrF failed

Not sure if the fmus have to be updated?

**Comment by dhblum** [comment]
I cannot reproduce the error you report.  I checked out ``ibpsa:master``, removed all docker images that were already built on my machine related to boptest testcase 1,2,3 and also removed the image ``michaelwetter/ubuntu-1804_jmodelica_trunk``.  Then, from the repo root directory, I ran ``$ make build TESTCASE=testcase1`` followed by ``$ make run TESTCASE=testcase1``.  I then ran the example by ``$ cd examples/python && python twoday_p.py``  with no problems.  I repeated for testcase 2 (running instead the example by ``$ cd examples/python && python szvav_sup.py``) and testcase 3, just starting the test case, but not running any example.  In all, I found no problems.

Can you be more specific on what is creating this error?

**Comment by SenHuang19** [comment]
@dhblum After set up a new ubuntu enviroment and tried the mostly updated master branch, I could not reproduce the error either. I believe this is a false alarm

**Comment by dhblum** [comment]
Great thanks!
