### ISSUE TITLE
Different pricing scenarios in reported cost KPI

### ISSUE THREAD

**Issue by dhblum** [ibpsa/project1-boptest#244]
Currently, the ``/kpis`` API call returns the cost KPI for the constant pricing scenario.  There is no way for a user to get the cost for the dynamic and highly dynamic pricing scenarios.  This issue is to add an API for the user to select the pricing scenario for which cost should be calculated.  Or, to add to the existing KPI report all three costs.  I am in favor of the former, as eventually, I think we need to standardize how to setup a given test, and selecting a price scenario is part of this.

**Comment by dhblum** [comment]
My proposal is to add:

Interaction|Request
-----------|--------
Receive current price scenario | GET ``price_scenario``
Set price scenario | PUT ``price_scenario`` with argument ``type=<'constant' or 'dynamic' or 'highly_dynamic'>``

**Comment by JavierArroyoBastida** [comment]
I'm surprised that we've overlooked this till now since specifying price scenario is an important feature. The solution that you propose looks good to me, and also prefer that one over showing all three costs.

**Comment by dhblum** [comment]
Implemented on https://github.com/ibpsa/project1-boptest/tree/issue244_setPriceScenario.

**Comment by dhblum** [comment]
Another idea is to implement the following:

Interaction|Request
-----------|--------
Receive current scenario settings | GET ``scenario``
Set scenario settings | PUT ``scenario`` with argument json: ``test_settings = {'electricity_price' : <'constant' or 'dynamic' or 'highly_dynamic'>, 'time_period' : <'summer' or 'winter' or 'shoulder' or 'annual'>, 'weather_forecast_uncertainty' : <'none' or 'low' or 'high'>}`` 

In this way, we already have a mechanism for setting all scenario parameters.

**Comment by JavierArroyoBastida** [comment]
That sounds good to me. I like having all scenario settings within the same dictionary. That will probably help with categorization of test case runs. Also agree with the scenarios that you propose. One think we may need to think though is whether the `annual` scenario needs to be initialized and how.

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/250.
