### ISSUE TITLE
OpenAI Gym interface

### ISSUE THREAD

**Issue by JavierArroyoBastida** [ibpsa/project1-boptest#248]
This issue is to create an OpenAI Gym interface around BOPTEST to facilitate plugging in controllers from the machine learning community. Similar initiatives have already taken place like in [here](https://git.isis.vanderbilt.edu/SmartBuildings/boptest-gym). This issue should avoid parallel developments and centralize efforts within this repository.

**Comment by dhblum** [comment]
A new repository has been created for this issue: https://github.com/ibpsa/project1-boptest-gym.  Please use that repository to bring up, discuss, and implement additional issues related to an openai gym interface.
