### ISSUE TITLE
ImportError of the Python examples

### ISSUE THREAD

**Issue by SenHuang19** [ibpsa/project1-boptest#249]
When using 

> Then, in a separate terminal, use $ cd examples/python/ && python testcase1.py

to start the python example, I got the following error

> Traceback (most recent call last):
  File "testcase1.py", line 20, in <module>
    from examples.python.custom_kpi import custom_kpi_calculator as kpicalculation
ImportError: No module named examples.python.custom_kpi

One solution to this is to add the boptest directory to the PYTHONPATH

**Comment by dhblum** [comment]
Perhaps we should add "Add root of the BOPTEST repository to the PYTHONPATH" in the Quick-Start documentation int he readme, as step 1. or 2. before or after "install Docker."
