### ISSUE TITLE
Specifying scenario time period

### ISSUE THREAD

**Issue by dhblum** [ibpsa/project1-boptest#270]
This issue is to enable the ``'time_period'`` parameter proposed in #244 in the comment https://github.com/ibpsa/project1-boptest/issues/244#issuecomment-721367335 for some initial test scenario definitions.

First, we must specify the time periods for each emulator.  I propose:

- We define test scenarios that last for two weeks, with a one week warmup-period utilizing baseline control.  The time period argument is defined by the middle day of the two weeks such that:

1. "cooling_peak" = day with the max 15-minute system cooling load in the year.
2. "cooling_typical" = day with the max 15-minute system cooling load that is closest from below to the median of all 15-minute maximum cooling loads of all days in the year.
3. "heating_peak" = day with the max 15-minute system heating load in the year.
4. "heating_typical" = day with the max 15-minute system heating load that is closest from below to the median of all 15-minute maximum heating loads of all days in the year.

- Systems that do not have cooling will only have the heating scenarios available.
- We'd need to only consider days 8 through 357 in the above determination if we want to avoid test scenarios that go through end/start of year.  

Then, for implementing in code.  I propose:

- We use the ``config.py`` file to define the days outlined above.
- ``testcase.py`` utilizes this information to invoke the ``initialize()`` function appropriately and define a flag that can be used to stop a simulation upon reaching the end of the time period.

Feedback would be great!

**Comment by JavierArroyoBastida** [comment]
This approach sounds reasonable to me. We may want to develop a script that upon being called runs the baseline controller and identifies the test scenarions as you propose. 
One doubt I have is: why in the `_typical` scenarios does the load need to be the closest from *below* (and not above) the median for both: heating and cooling?
Also for the implementation I think what you suggest makes sense but, is it the intention then to remove the `start_time` and `warmup_time` arguments from the `initialize` API call? I would let these be optionally used: if not specified, then the default is that the testcase parses the period from the scenario. If used, then the scenario is disregarded and the value sent is used. The reason I'm pointing this out is that there should be some flexibility to use the testcase for training models/algorithms out of the testing period.

**Comment by dhblum** [comment]
Thanks @JavierArroyoBastida for the feedback.  

To your first point, I agree and already started.
To your second point, from above seems just as valid I suppose.  Would need to pick one.
To your third point, my thought was not to remove ``/initialize``, rather that the ``time_period`` in ``/scenario`` would perform the same function but with specific ``start_time`` and ``warmup_time`` parameters.  Whichever the user calls last between ``/initialize`` and ``/scenario`` (with ``time_period``) would dictate from where the simulation is started.

**Comment by haraldwalnum** [comment]
Regarding identification of a scenario with both heating and cooling I have a suggestion:
Let H and C be the daily heating and cooling loads, respectively. Then the scenario can be defined by:

max((H_i+C_i) - abs(H_i-C_i))

If no days has both heating and cooling, the sampling rate can be lowered

**Comment by dhblum** [comment]
@haraldwalnum Thanks for the suggestion!  It took me a bit to understand, but I see now the abs(H_i-C_i) is meant to penalize a day that has a high (H_i+C_i) but is actually just dominated by a large H_i or C_i.  It seems good to me.

**Comment by dhblum** [comment]
@JavierArroyoBastida FYI I'm working on an implementation that connects days.json with the scenario.

**Comment by dhblum** [comment]
See https://github.com/ibpsa/project1-boptest/tree/issue270_scenarioTime_2 for implementation so far.

**Comment by JavierArroyoBastida** [comment]
Looking great so far, thanks for the implementation! I'm not working on this now so there is no risk to overlap, will let you know otherwise.

**Comment by dhblum** [comment]
@JavierArroyoBastida What do you think about changing the existing test case unit tests for winter/summer/shoulder to use the time periods defined by days.json instead?  I think this will cut down on excess tests that do the same thing.

**Comment by JavierArroyoBastida** [comment]
I have a bit of mixed feelings. I like the idea of having the tests running in the periods from days.json since those are the periods we should care most about. Also sounds reasonable to avoid a summer test when there's no cooling in the test case. However, those tests can be useful e.g. when you make changes in a baseline heating controller but want to make sure that the rest of the model remains unchanged. In those cases I usually check that the tests pass without changing references for the period that shouldn't be affected by the changes in the controller. It's arguable whether it's worth having those tests still, but just wanted to mention that they can be useful.

**Comment by dhblum** [comment]
Point well-taken about testing models with no cooling system still in a summer period.

**Comment by dhblum** [comment]
What about testing the scenario periods, and then adding as needed for other periods?  The unit tests for each emulator are defined separately.

**Comment by JavierArroyoBastida** [comment]
That sounds good. Actually, we can start by using the scenario periods only for now. If we see that other periods can be really useful we can extend the tests in each specific emulator as needed.

**Comment by dhblum** [comment]
I think you're right that there is value in testing, for instance, a summer period for bestest_hydronic even though it is not included in one of the days.json periods to check that the system and controller still behaves as expected.

**Comment by JavierArroyoBastida** [comment]
Yes I think so! But feel free to trim tests to include only the scenario periods in this PR if you like. We'll extend with other periods as we need them.

**Comment by dhblum** [comment]
Alright, implementing now.  The test periods are much longer than two days, which is what the summer/shoulder/winter tests are now.  So the result file size will increase and so will the time it takes to run the tests.  I'm going to implement so that not every output and input is checked, but the KPIs will be and then the trajectories of a select few key points.

**Comment by JavierArroyoBastida** [comment]
That sounds great!

**Comment by dhblum** [comment]
One more point.  I'm thinking about the need for a stop flag that is set for when a time period scenario is specified.  So, set the end time of the test and do not allow the simulation to proceed past that time.  The flag would be set with use of ``/scenario`` with a ``'time_period'``, but not set if a user just uses ``/initialize``.  Otherwise, there is no enforcement of when the test time period ends.

**Comment by JavierArroyoBastida** [comment]
That's a great idea. It had actually crossed my mind before so I'm happy you're bringing it up. Also agree with the way of implementing it that you're suggesting.

**Comment by dhblum** [comment]
Add to to-do here: https://github.com/ibpsa/project1-boptest/issues/270#issuecomment-781697871.

**Comment by dhblum** [comment]
Unit tests implemented in https://github.com/ibpsa/project1-boptest/commit/8fba8c908888a1544675965396d540f90f4e5b70.

**Comment by dhblum** [comment]
Test end time flag implemented in https://github.com/ibpsa/project1-boptest/commit/a8765177d977d49cc74c60e2a8c67c8a361e53ae.

**Comment by JavierArroyoBastida** [comment]
@dhblum, when moving from using `/initialize` to using `/scenario` with `time_period` specified on it I realized that these return different arguments. The former is returning measurments at the end of the initialization: https://github.com/ibpsa/project1-boptest/blob/ced9ef5f7ca2c4a86c3537023ece083007dfd544/restapi.py#L82 while the latter is returning the just set scenario settings: https://github.com/ibpsa/project1-boptest/blob/ced9ef5f7ca2c4a86c3537023ece083007dfd544/restapi.py#L176 
Since the latter is sort of substituting the former for spcefic scenario settings, wouldn't it be better if both return measurments at the end of the initialization? 
this relates to https://github.com/ibpsa/project1-boptest/issues/270#issuecomment-758803577 in this same thread. 
I can come up with a proposal if you agree.

**Comment by JavierArroyoBastida** [comment]
Also, shouldn't the following line:
https://github.com/ibpsa/project1-boptest/blob/ced9ef5f7ca2c4a86c3537023ece083007dfd544/testcase.py#L516
Be like:
`start_time = self.days_json[key]*24*3600`? I mean, without subtracting the `warmup_period=7*24*3600`, as that one is subtracted later at:
https://github.com/ibpsa/project1-boptest/blob/ced9ef5f7ca2c4a86c3537023ece083007dfd544/testcase.py#L287

**Comment by dhblum** [comment]
Our proposed tests to start were two-week tests with a one-week warmup period where the "day" defined was the middle day of the two weeks.  So line 516 implements the start time as one week before the "day" defined in days.json.  And then the warmup period is one week before that.

You bring up a good thing to think about with the return of /scenario using time_period.  The thing is, what do you return if only "electricity_price" is used?  I think I'd rather not have different returns for the same API call.  I'm not sure the best answer yet.  One thought is returning a json with one key related to setting electricity price (could just be a True if successful) and/or one key for setting time period (the initial measurement).

**Comment by JavierArroyoBastida** [comment]
Ok I see, I understood that the tests were defined to last for two weeks from which one was used for initialization. It's clear now.

Regarding the return from `/scenario`, I'm not sure what's best either. Returning a json can indeed be a solution, but a similar question arises: what would you return in the time period key if only "electricity_price" is used? or would there be no time period key in that case?

**Comment by dhblum** [comment]
Yea no time period key in that case.

**Comment by dhblum** [comment]
Proposed updated return dictionary in https://github.com/ibpsa/project1-boptest/commit/fc8479edff04b6d29bba8d73f52fd16551e6f1e4 of https://github.com/ibpsa/project1-boptest/tree/issue270_scenarioTime_2.

**Comment by dhblum** [comment]
Updated to-do list.  In latest commits to https://github.com/ibpsa/project1-boptest/tree/issue270_scenarioTime_2, I've:

- Add finding mixed heating and cooling days proposed in https://github.com/ibpsa/project1-boptest/issues/270#issuecomment-774719263
- Add ``days.json`` documentation to Design Requirements and Guide
- Update ``bestest_air`` with days.json based on Dymola results, add mix day, add time period to scenarios section of documentation, update reference results.  @JavierArroyoBastida I think the same type of documentation should be added to bestest_hydronic cases eventually (see section "Time Periods" under "Scenarios").  Could be separate issue after this is merged.
- Update ``testcases/README.md`` with summary of available scenarios

**Comment by JavierArroyoBastida** [comment]
@dhblum your changes are looking good to me. Thanks for implementing the return dictionary and the method to identify mix day.

**Comment by dhblum** [comment]
Updated to-dos with commits up to https://github.com/ibpsa/project1-boptest/commit/e76baf2d4f0f28f9b8680fce08bb3f0a5da84d33:
- Added minimalistic example using scenarios api for test case ``testcase1``.
- Updated documentation in test case ``bestest_air`` to include start and end time of each time_period scenario option.
- Updated ``README.md`` to include new example and improve ``/scenario`` description.

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/314.
