### ISSUE TITLE
Adding more example controllers

### ISSUE THREAD

**Issue by SenHuang19** [ibpsa/project1-boptest#277]
This issue is to create new example controllers for the newly merged testcases

**Comment by dhblum** [comment]
Hey @SenHuang19 I'm a little confused on what exactly needs to be updated in the example controllers based on API changes?  They are all passing tests.

Can you be more specific about which testcases and what types of example controllers you want to add for them?

**Comment by dhblum** [comment]
Closed to be considered in the future.
