### ISSUE TITLE
Testing for service

### ISSUE THREAD

**Issue by dhblum** [ibpsa/project1-boptest#282]
This issue is implement testing for boptest-service.  To start, it can be based on existing testing, but use service to deploy test cases for API testing.

**Comment by kbenne** [comment]
The boptest-service branch is passing now. I'm not sure it is the time to close this issue as the python2 tests are disabled, and also the Julia and javascript tests. I think they can be re-enabled though. Progress.

**Comment by dhblum** [comment]
Closing this with Service development moved to https://github.com/NREL/boptest-service, which has tests.
