### ISSUE TITLE
Testcase: bestest_hydronic_heat_pump setpoint control

### ISSUE THREAD

**Issue by haraldwalnum** [ibpsa/project1-boptest#299]
@JavierArroyoBastida. I have tested a bit on the hydronic heat pump model, trying to implement a controller that modifies the temperature setpoint for the zone. However I am struggling a bit with the implementation due to how the setpoint overwrite block is implemented. 
As of now, the baseline controller adds an offset to the setpoint after the overwrite block (0.2 or 5.5K). At the same time, the setpoint overwrite blocks are limited to the comfort range. E.g. one can not lower the setpoint lower than 5.5 K above the comfort limit (288.15K) when there are no occupants. 

One solution would be to lower the minimum temperature allowed in the overwrite block.
Maybe a solution that is more understandable for the users is to insert an overwrite block between switch1 and conPI

**Comment by JavierArroyoBastida** [comment]
That's a good point you're raising. Maybe we should consider both solutions actually. I think both are realistic and using either heating/cooling setpoints or directly the temperature setpoints depends on how a thermostat is configured. I'll come up with an implementation for this.

@dhblum FYI. Notice that building physiscs and baseline control will not change so it should be an easy edit.

**Comment by haraldwalnum** [comment]
Thanks. Another more general note on the documentation for all the emulators, is that it would be nice to have a system sketch (P&ID), showing the connections and inputs and outputs. This could just be a screenshot of the modelica model, but make sure that the names of the input/output blocks are visible. 
Now it is quite hard to understand the model without opening it in Dymola, and I quess this should not be a prerequisite for those who want to test it.

**Comment by dhblum** [comment]
I'm letting @icupeiro know of this potential change.

And @haraldwalnum your point on schematics is well-taken and I think would be good particularly as systems get more complex.

**Comment by dhblum** [comment]
New, separate, issue for https://github.com/ibpsa/project1-boptest/issues/299#issuecomment-788838326 opened at #301.
