### ISSUE TITLE
Set point Offset in BESTEST Hydronic Test Case

### ISSUE THREAD

**Issue by dhblum** [ibpsa/project1-boptest#303]
@JavierArroyoBastida I noticed in the ``bestest_hydronic`` test case that there is an offset given to the zone heating set point.  I think this is similar to what was done in the ``bestest_hydronic_heat_pump`` case where the offset should be part of the baseline controller, and the overwriting of the set point should be after such an offset.  See https://github.com/ibpsa/project1-boptest/issues/299 and https://github.com/ibpsa/project1-boptest/pull/300.

**Comment by JavierArroyoBastida** [comment]
Good point. I'm adding this to my list. I'll let you know when I start implementing the change.

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/338.
