### ISSUE TITLE
Update Uccle.TMY

### ISSUE THREAD

**Issue by JavierArroyoBastida** [ibpsa/project1-boptest#312]
Both bestest hydronic cases use the Uccle.TMY weather file. This file is expected to be modified soon because the solar irradiation has been found to be shifted by one hour, see: https://github.com/open-ideas/IDEAS/issues/1206. This issue is to update the cases accordingly.

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/320.
