### ISSUE TITLE
Update Uccle.TMY 2

### ISSUE THREAD

**Issue by JavierArroyoBastida** [ibpsa/project1-boptest#321]
I've just realized that https://github.com/ibpsa/project1-boptest/pull/320#pullrequestreview-643304332 updates the weather files in the model but not in the resources folder of the hydronic cases. The weather data exposed in the case does therefore not correspond to the data in the model. This is to change that.

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/322.
