### ISSUE TITLE
Bestest hydronic fmus

### ISSUE THREAD

**Issue by JavierArroyoBastida** [ibpsa/project1-boptest#325]
Looks like in https://github.com/ibpsa/project1-boptest/pull/323 I did not update the wrapped fmus of the hydronic cases with the right data that was fixed in https://github.com/ibpsa/project1-boptest/pull/322. This is to update these fmus.

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/326.
