### ISSUE TITLE
Computational Time Ratio KPI Calculation

### ISSUE THREAD

**Issue by dhblum** [ibpsa/project1-boptest#327]
In the Design Requirements and Guide, Computational Time Ratio is defined to allow for variable control step size.  The API also allows a user to change a step size mid simulation.  However, the implementation of the KPI calculator ([here](https://github.com/ibpsa/project1-boptest/blob/538acebc318e1d5461434cdef1e883ef3e3b4a8c/kpis/kpi_calculator.py#L520)) uses the ``testcase.step`` attribute, which would just be the last step size used, but not a record of those used through the duration of the simulation.  I think this should be rectified by storing the step sizes so the Design Requirements and Guide spec and API implementation can be satisfied.

**Comment by dhblum** [comment]
Currently, the Design Requirements and Guide has computational time ratio defined as the average computational time divided by the average simulation step:

<img width="335" alt="Screen Shot 2021-05-13 at 5 18 49 PM" src="https://user-images.githubusercontent.com/19480999/118189113-5e07a300-b40f-11eb-88f6-b86cc276ecb6.png">

I think is is incorrect to say that sum(a) / sum(b) = sum(a/b).  For instance, consider 10 steps where if at every step the controller takes 1s and the simulation step is 10 s, then the value of the LHS = 0.1 where the value of the RHS = 1.0.

I think instead this KPI is meant to take the average ratio of t_c and T_s over all time steps k, which would require dividing the RHS by n.

**Comment by dhblum** [comment]
Other thoughts welcome, FYI @SenHuang19 @JavierArroyoBastida.

**Comment by SenHuang19** [comment]
I totall agree with you about " sum(a) / sum(b) != sum(a/b)"
I suggest we either do the average or include both mean and std

**Comment by SenHuang19** [comment]
Besides, should we consider if a controller fails to calculate the output in time, we have to sustain the value of control signals from a previous successful run?

**Comment by dhblum** [comment]
I agree with sticking with the average right now, and not also including std.

Regarding if the controller fails, since the current implementation is controller-blocked (e.g. the controller needs to advance time when ready), it is up to the controller to identify it has failed and advance time with the previous successful run.

**Comment by JavierArroyoBastida** [comment]
I totally agree that we should rectify this to take the average ratio of t_c and T_s over all time steps k. I'd also avoid std just to not complicate things since so far every KPI has a single scalar result associated to it. I think the implementation should be quite simple, I'll let you know if I get started with this. Please do the same if you do so that we don't overlap.

**Comment by dhblum** [comment]
Ok thanks!  Will do.

**Comment by dhblum** [comment]
@JavierArroyoBastida I'm implementing a fix.  Will make a PR.

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/329.
