### ISSUE TITLE
Correct multizone residential schema

### ISSUE THREAD

**Issue by JavierArroyoBastida** [ibpsa/project1-boptest#333]
It is found in [here ](https://github.com/ibpsa/project1-boptest/pull/330#discussion_r646426409) that the lengths indicated in the multizone residential hydronic test case are either wrong or outdated. It is indicated a length of 14.4 m and a width of 8.3 m. However, inspecting the lengths as indicated at the beginning of the model per zone and orientation I see that these should be:

`length=(Spe_Salon_Sud+Spe_Chambre1_Sud+Spe_Chambre2_Sud)/HSP=6.6+3.1+3=12.7`

`width=(Spe_Salon_Est+Spe_Garage_Est)/HSP=2.6+5.4=8`

This issue is to correct the schema and the associated documentation accordingly.

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/334.
