### ISSUE TITLE
Bestest Hydronic HP images in Chrome

### ISSUE THREAD

**Issue by JavierArroyoBastida** [ibpsa/project1-boptest#351]
The images used for documenting the bestest_hydronic_heat_pump case are not visible in `doc/index.html` when using Chrome. 
Removing the last `\` in the `src` argument for their import has proven to resolve the problem. This issue is to implement this edit.

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/352.
