### ISSUE TITLE
Continuous integration testing

### ISSUE THREAD

**Issue by dhblum** [ibpsa/project1-boptest#36]
This issue is to add continuous integration testing with [Travis](https://travis-ci.org/).

**Comment by dhblum** [comment]
@mwetter I've pushed an initial implementation of a travis yml to a branch (https://github.com/ibpsa/project1-boptest/tree/issue36_ciTravis, see https://github.com/ibpsa/project1-boptest/commit/74c9782c6696c0f7ad1cc4813426dad0cb6509fa).  How do you recommend I initiate travis and test the ci?

**Comment by mwetter** [comment]
@dhblum : I enabled CI testing, please see https://travis-ci.org/ibpsa/project1-boptest/branches

**Comment by dhblum** [comment]
Great, thank you.

**Comment by dhblum** [comment]
https://github.com/ibpsa/project1-boptest/tree/issue36_ciTravis_b is passing.

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/79.

**Comment by dhblum** [comment]
Add build icon.

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/81.
