### ISSUE TITLE
Cannot import parser

### ISSUE THREAD

**Issue by JavierArroyoBastida** [ibpsa/project1-boptest#38]
This issue is only to change the name of the "parser" folder as it is already a builtin python module. It doesn't cause any problem in Linux but it does in windows. See:

[link1](https://docs.python.org/2/library/parser.html)

[link2](https://bytes.com/topic/python/answers/562469-import-parser-does-not-import-parser-py-same-dir-win )

[link3](https://forum.learncodethehardway.com/t/importerror-unknown-location/2034)

[link4](https://github.com/m4ll0k/WAScan/issues/10)

Suggested names:

- compiler
- parsing
- fmugenerator

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/39.

**Comment by dhblum** [comment]
Need to edit readme.

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/40.
