### ISSUE TITLE
Unit tests failing from javascript Docker

### ISSUE THREAD

**Issue by dhblum** [ibpsa/project1-boptest#389]
Unit tests that passed successfully a couple weeks ago in https://github.com/ibpsa/project1-boptest/pull/377 are now failing due to an update needed for the Python libraries used in the javascript example.  Also seems to be a problem seen in https://github.com/ibpsa/project1-boptest/pull/272, which was fixed by commit https://github.com/ibpsa/project1-boptest/pull/272/commits/49ebcc497d5f5335715754af330668f6698c686a.

I suggest making this commit/fix to master so that all development branches can be updated with the patch for this specific issue.

**Comment by dhblum** [comment]
@SenHuang19 Sound ok?

**Comment by SenHuang19** [comment]
yes, sure.

> @SenHuang19 Sound ok?

**Comment by dhblum** [comment]
Ok great, making a PR soon.

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/390.
