### ISSUE TITLE
Provide a list of points to /results

### ISSUE THREAD

**Issue by dhblum** [ibpsa/project1-boptest#398]
This issue is to suggest making the ability to provide a list of points to the /results API call, instead of requiring one at a time.  The return would be the same object, just with additional arrays of point data.  

While I acknowledge the potential memory issues of calling for large amounts of data (e.g. https://github.com/ibpsa/project1-boptest/issues/240), this would reduce the need for excessive network requests (say in a long for-loop), which could otherwise bottleneck the system.  And, the user would have control over the amount of data returned at one time if memory becomes too much an issue.

**Comment by dhblum** [comment]
We may also consider similarly for forecast data when addressing https://github.com/ibpsa/project1-boptest/issues/356.

**Comment by EttoreZ** [comment]
@dhblum would you mind create the branch issue398_ListOfPointsResultsAPI so I can make a pull request? All the unit tests passed on bestest_air and bestest_hydronic. However, there are still a couple of things to check before the pull request is completely ready:

- [ ] Check that python examples run correctly
- [ ] Check that Juilia examples run correctly
- [ ] Make change for Javascript examples
- [ ] Check comments and documentation

**Comment by dhblum** [comment]
Thanks @EttoreZ.  Branch created here https://github.com/ibpsa/project1-boptest/tree/issue398_ListOfPointsResultsAPI.  Make the PR and unit tests will check bullets 1 and 2.  3 shouldn't be too hard to add if I have to, and I can review comments/docs.

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/480.
