### ISSUE TITLE
Missing and wrong documentation for initialize

### ISSUE THREAD

**Issue by tstorek** [ibpsa/project1-boptest#408]
HI,

Initialize simulation to a start time using a warmup period in seconds. 
According to the docs one should use the following for this:

```python

res = requests.put(url=urljoin(http://localhost:5000, 'initialize'),  data = {'start_time': 0,  'warmup_time': 0})
```

This does not work because it must be `warmup_period`.
Additionally, it would be good to document that this does also rest the state of the model and that both arguments are required.

Are there actually default values for this?

**Comment by dhblum** [comment]
Thanks for reporting!  We will make the fix in the documentation.

When the test case is first deployed it initializes with a default start_time = 0 and warmup_time = 0.   But there are no defaults for when a user calls /initialize.  When a user calls /scenario with a particular "time_period" specification, there are defaults that BOPTEST uses according to that specification to put the test case at the start of the scenario time period with consistent initial conditions.

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/410.
