### ISSUE TITLE
TestCase: Two Zone Hydronic Apartment

### ISSUE THREAD

**Issue by EttoreZ** [ibpsa/project1-boptest#409]
This issue is to create the two zone hydronic test case, used for the MPC formulation comparison manuscript, as specified in IBPSA Project 1 WP1.2.
I will make a pull request on the branch issue409_hydronicMPCformulations once it's ready for review.

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/489.
