### ISSUE TITLE
consider hosting the testcase docs directly?

### ISSUE THREAD

**Issue by epaulson** [ibpsa/project1-boptest#427]
I love that each of the BOPTEST testcases come with a some documentation that explains the details of the testcase and what's being simulated. Would it be possible to find a place somewhere on https://ibpsa.github.io/ that those docs could be deployed? GitHub unfortunately doesn't render html when it's checked in (like it does with Markdown) so it's a little clunky to share details about a testcase.

Thanks!

**Comment by dhblum** [comment]
Yes, this is being actively addressed in #214.  A version is available here https://ibpsa.github.io/project1-boptest/testcases/index.html, though the web page as a whole is still being worked on.

Closing as duplicate to #214.
