### ISSUE TITLE
CCAI Wokshop

### ISSUE THREAD

**Issue by JavierArroyoBastida** [ibpsa/project1-boptest#433]
This issue is to create the materials for the building forecasting and control workshop that will be held in the [CCAI Summer School](https://www.climatechange.ai/events/summer_school2022). The workshop will use the BESTEST hydronic heat pump case of BOPTEST for both generating static data to teach building load forecasting and controlling a building emulator to teach advanced HVAC controls. More specifically, the workshop will be divided into the three following parts:
1.	Common introduction to HVAC systems and motivation for building load forecasting and control 
2.	Load forecasting 
3.	Control with the BOPTEST framework 

Part 2 will reuse content from [this Colab notebook](https://colab.research.google.com/drive/1o86HKTerVnEi0xjlKOj7uoYkS9fmnrRC). 

Part 3 will reuse content from [this Colab notebook](https://github.com/ibpsa/project1-boptest/blob/master/docs/workshops/BS21Workshop_20210831/Introduction_to_the_BOPTEST_framework.ipynb). 

I suggest merging both in the same notebook to provide a coherent story. 
I also suggest generating the load forecasting data using the emulator baseline controller. This would require an introductory explanation of how to start up a BOPTEST case but we can refer for later (Part 3) for further explanation.

**Comment by JavierArroyoBastida** [comment]
@dhblum I eventually addressed this issue in [a branch of the BOPTEST-Gym repository](https://github.com/ibpsa/project1-boptest-gym/pull/106). Particularly, the materials have been added [here](https://github.com/ibpsa/project1-boptest-gym/tree/master/docs/tutorials/CCAI%20Summer%20School%202022). Should we add them to this repository as well? or maybe just add a link? Or maybe nothing since the tutorial is more focused on BOPTEST-Gym. Please let me know your thoughts.

**Comment by dhblum** [comment]
I think it's best to keep the material in one place.  For this repo, what about adding a docs/tutorials/CCAISummerSchool2022/README.md that links to the material in the gym repo?

**Comment by JavierArroyoBastida** [comment]
I agree. Will do that.

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/477.
