### ISSUE TITLE
Advancing simulations and passing input for FMUs

### ISSUE THREAD

**Issue by davidefop** [ibpsa/project1-boptest#434]
I am trying to recreate the “advance” function used by BOPTEST (project1-boptest/testcase.py). Basically, I’d like to run a simulation of a Modelica model FMU from a python master code using pyfmi, while interacting with the model at each desired timestep with a control input. The model and its FMU are generated in the OpenModelica environment; inputs are set using Buildings.Utilities.IO.SignalExchange objects, and the fmu is extracted from a “wrapped.mo” model that sets the input real value along its Boolean value to activate the SignalExchange object. 
As far as I can infer from the code, it uses the pyfmi “simulate” function instead of a do.step approach:

`simulate(start_time = start_time, final_time = end_time, options=self.options, input=input_object)`
(line 144 of project1-boptest/testcase.py)

However, when recreating that bit of code, it appears that the system does not store all the necessary states of the whole system each time the function “simulate” is called, resulting in the system not evolving but rather restarting all its states from their initial values. 
How can the function simulate be called at each timestep while keeping track of all the evolving system states, so that it works as do.step, allowing control signals to be passed as input to the model? I must assume simulate is preferred over do.step to possibly integrate spawn of Energyplus as well and support Model Exchange FMUs.  

Details on software and setup:
•	OS: Windows 10
•	OpenModelica v1.19.0-dev.beta1 (64-bit) 
•	FMI version: 2.0
•	Python 3.8 (minor adjustments already performed, the code per se runs smoothly)

**Comment by dhblum** [comment]
Make sure you set ``options['initialize']=False`` for subsequent ``simulate`` calls after the initial one.  BOPTEST does this here: https://github.com/ibpsa/project1-boptest/blob/17b1172623088c80db3d590ccb48f455a08c57dc/testcase.py#L151.

pyfmi's ``simulate`` is preferred over ``do.step`` because in addition to initialization, it handles time and state events, as well as allows use of ME FMUs, which can more computationally efficiently output trajectory data at high resolutions.

**Comment by davidefop** [comment]
Thanks, it worked. The issue can be considered solved as far as I'm concerned

**Comment by dhblum** [comment]
Great to hear, thanks for closing @davidefop.
