### ISSUE TITLE
Error starting Boptest example

### ISSUE THREAD

**Issue by MaPaKo** [ibpsa/project1-boptest#437]
I am a PhD student in building control and want to use Boptest for an MPC study. But I can't get it to run. I copied the code from Fig. 3 [1] . It executes until this line: 

- _y = requests.put("{0}/scenario".format(url), data=scenario).json()["time_period"]_

which responds with _'KeyError: time_period'_.

I can't find the source of the problem. Also, the paper states that Fig. 3 comes from the file _testcase1_scenario.py_. However, the corresponding file contains completely different code. Is the code from the paper still supposed to work, or has the library changed so much since then that it is no longer functional? 

[1] https://www.tandfonline.com/doi/full/10.1080/19401493.2021.1986574

**Comment by MaPaKo** [comment]
Hello Javier, 
Thanks for the quick response. The same thing happens with _testcase1_scenario.py_. I use:
- Boptest 0.2.0. Pulled from Git yesterday. 
- Windows 10
- Anaconda Spyer with Python 3.8 


**Here is the code: (I replaced the # with %)**

% LINK
from sys import path
path.append(r"C:\ModelicaToolbox\BOPTEST_020\examples\python")

% GENERAL PACKAGE IMPORT
import requests
import numpy as np

% TEST CONTROLLER IMPORT
from controllers import pid

% SET TEST PARAMETERS
% Set URL for test case
url = "http://127.0.0.1:5000"

% Set testing scenario
scenario = {"time_period":"test_day", "electricity_price":"dynamic"}

% Set control step
step = 300

% GET TEST INFORMATION
% Get test case name
name = requests.get("{0}/name".format(url)).json()

% Get inputs available
inputs = requests.get("{0}/inputs".format(url)).json()

% Get measurements available
measurements = requests.get("{0}/measurements".format(url)).json()

% RUN TEST CASE
% Set control step
requests.put("{0}/step".format(url), data={"step":step})

% Set test case scenario
% test = requests.put("{0}/scenario".format(url), data=scenario).json()
y = requests.put("{0}/scenario".format(url), data=scenario).json()["time_period"]

% Record test start time
start_time = y["time"]

% Simulation loop
while y:
    # Compute control signal
    u = pid.compute_control(y)
    # Advance simulation with control signal
    y = requests.post("{0}/advance".format(url), data=u).json()
    
% GET RESULTS
% Get KPIs
kpi = requests.get("{0}/kpi".format(url)).json()

% Get zone temperature over test period
args = {"point_name":"TRooAir_y", "start_time":start_time, "final_time":np.inf}
res = requests.put("{0}/results".format(url), data=args).json()

**Comment by JavierArroyoBastida** [comment]
If you cannot run `testcase1_scenario.py` it may be a problem with the test case container, in which case I'm surprised that you even got to:
```
y = requests.put("{0}/scenario".format(url), data=scenario).json()["time_period"]
```
Can you print `name`, `inputs` and `measurements` to make sure that these are not empty variables?
If so, it is clear that the Docker container is not deployed correctly. In that case, can you make sure that:
1. You have followed the quick-start instructions to deploy a test case in the [README](https://github.com/ibpsa/project1-boptest). 
2. If so, you're using the BOPTEST master branch, that is commit: 11e7e2c178b68967ce24dd8a5eae3c4d783037a6 (I could just run example `testcase1_scenario.py` in my laptop after deploying testcase1 from that BOPTEST commit.

**Comment by MaPaKo** [comment]
These variables all look OK. They have 1, 8 and 36 elements. Yes, I use that commit. I follow the README, as far as I can tell. 

- Should I see any Boptest related environmental variables?
- Is there another way to check the building model and the connection?

BTW this line doesn't execute either: _sys.path.insert(0, '/'.join((os.path.dirname(os.path.abspath(__file__))).split('/')[:-2]))_

**Comment by JavierArroyoBastida** [comment]
Can you show here what you get when printing those variables? For `testcase1` it should look like:
![image](https://user-images.githubusercontent.com/22677958/173806491-0a094f48-d665-40fe-b008-60246f022f6d.png)
Also, in your console, when starting up the container you should see something like:
![image](https://user-images.githubusercontent.com/22677958/173806748-0bb1d43e-0b6c-4635-b08e-dba43a03e447.png)

is that the case?
You do not need to see any BOPTEST-related environment variables. As far as the container is running and listening to port "http://127.0.0.1:5000/" you should be able to interact with it. Seeing the right `name`, `inputs`, and `measurements` would prove that the connection is right and thus it is a problem with setting the scenario. I see that you are using 
```
scenario = {"time_period":"test_day", "electricity_price":"dynamic"}
```
Note that the "test_day" scenario is only used by `testcase1` for testing. Are you sure you're running testcase1 and not other test case? Note that different test cases may have different scenarios: see the available scenarios [in this table](https://github.com/ibpsa/project1-boptest/tree/master/testcases). 

Another possibility is that you're somehow using an older corrupted BOPTEST image. You can force to re-build the image by running:

```
docker rmi boptest_base
```
previously to `docker-compose up`.

**Comment by MaPaKo** [comment]
I misunderstood how the testcases work. I tried to run it with _bestest_hydronic_heat_pump_. It seems to work with the correct model. However, I don't see the run statistics in the PowerShell.

**Comment by dhblum** [comment]
The reason it did not work before was because ``"test_day"`` is only a time period scenario for ``testcase1``.  You can see the available scenarios for each test case here: https://github.com/ibpsa/project1-boptest/tree/master/testcases.

**Comment by dhblum** [comment]
This issue seems to be resolved.
