### ISSUE TITLE
Reduce travis unit test job time

### ISSUE THREAD

**Issue by dhblum** [ibpsa/project1-boptest#450]
The ``make test_all`` unit tests run within a single job are approaching the 2 hour time limit for travis as seen here: https://app.travis-ci.com/github/ibpsa/project1-boptest/jobs/577415219.  This issue is to either reduce the run time of the ``make test_all`` job, or to split the build into multiple jobs, for instance running each test in its own job.

**Comment by dhblum** [comment]
@kbenne FYI opening this issue to address.

**Comment by kbenne** [comment]
Good deal. It seems like there should be plenty of low hanging fruit that will yield much more efficient testing. I wonder if the strategies diverge between service and master? I'd rather not diverge if possible.

**Comment by dhblum** [comment]
Just took a quick look at https://github.com/ibpsa/project1-boptest/blob/issue448-service-submit/testing/makefile.  If we split the tests into individual jobs, I think what I proposed in https://github.com/ibpsa/project1-boptest/blob/split_travis_jobs/.travis.yml should work for service branches too.  This doesn't make the tests more efficient, just breaks jobs up into smaller chunks so they don't run into timeout problems.  But the whole test build will take longer to complete.  There's some optimization there available, like I'm not sure both the jm and boptest_base image need to be built for every test necessarily.

The alternative is to make the the one job with all tests more efficient.  If for Service, one of these things means provisioning all at once in the beginning, I don't think it's much of a divergence than already exists.  Already, the Service ``makefile`` uses a provision command (e.g.  ``cd .. && make provision TESTCASE=multizone_residential_hydronic``) within individual tests which doesn't exist in main.  These could be removed and combined into a single command within ``test_all`` at the beginning, similar to use of ``build_jm_image`` and ``build_boptest_image`` there.  Similar can be done in main for things like building the javascript and julia images.  But, in both cases, then the individual tests can't be run independently, which could be annoying for unit testing during development (so don't always have to run all tests).  Or, we put in sort of if-then clauses to check what case is being run.

**Comment by kbenne** [comment]
In the interest of wrapping up 0.3.0 I'm favoring a two prong approach. For the near term, I think I'd like to bring your split approach over to service.

After we wrap 0.3.0 I'd like to pursue building out one provision at the start of the whole thing, with some kind of logic to keep development convenient.

**Comment by dhblum** [comment]
Ok, then I say try the splitting on the service branch(es) and lets see how it goes.  One thing I'm not sure though is if the jobs are split, how they can share resources across jobs.  To do a single provisioning, we may then have to go back to the single job test_all method.

**Comment by kbenne** [comment]
Yeah I suspect we would have to go back to test_all. I guess I could extract the boptest-service build and provision steps and try I single job. You're not wrong, it doesn't look too bad. The developer experience would just be that you have to `docker-compose up` before running the tests. Not too much different from needing to build the jm image now.

**Comment by dhblum** [comment]
Ok, so want to try that?  I think on main I will move the building of javascript and julia controllers to the beginning as well.

**Comment by kbenne** [comment]
I just went back on what I said above and went ahead and tried to optimize the service tests a little bit, by avoiding the repeated build/start/stop of service.

https://github.com/ibpsa/project1-boptest/commit/267b2aae52aaa7be08b66e7d4e91acbc69e71223

Service has not been running the Julia and Javascript tests.

**Comment by dhblum** [comment]
What's the ``make -C`` do?

We have timeout errors on the main too.  So I'm going to move javascript and julia so build only once in ``test_all``.

**Comment by kbenne** [comment]
Just avoids the use of `cd`

**Comment by kbenne** [comment]
Does each `script:` element get its own time limit? Or do you have to have unique `job:` elements? 

https://github.com/ibpsa/project1-boptest/commit/18058cdfef69160fd589b16a9d32097d8770e327#diff-6ac3f79fc25d95cd1e3d51da53a4b21b939437392578a35ae8cd6d5366ca5485R31

**Comment by dhblum** [comment]
Yea, the way I have it there because they are under ``include`` each script element becomes a job (gets its own time limit).

**Comment by kbenne** [comment]
I wonder if it gets its own context too. Like a entirely new VM.

**Comment by dhblum** [comment]
That's what I was saying in my [comment](https://github.com/ibpsa/project1-boptest/issues/450#issuecomment-1192686980) before: "One thing I'm not sure though is if the jobs are split, how they can share resources across jobs. To do a single provisioning, we may then have to go back to the single job test_all method."

**Comment by kbenne** [comment]
I saw that you tried to abstract this into a function. https://github.com/ibpsa/project1-boptest/blob/split_travis_jobs/.travis.yml#L24

I guess it didn't work huh?

**Comment by dhblum** [comment]
You mean here?  https://github.com/ibpsa/project1-boptest/commit/2f6875a9e1cb40da8683845962f4fb973107cbe3

No, didn't work, the job matrix didn't come out right.

**Comment by dhblum** [comment]
Implemented solution here is split tests into multiple jobs.  Refining the unit test and travis configuration code will be tackled in a future issue.

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/454 and https://github.com/ibpsa/project1-boptest/commit/61a09ab1e2d6c7b6265f5d5c4385d9fe54a2be60.
