### ISSUE TITLE
Generating FMUs of Spawn models

### ISSUE THREAD

**Issue by davidefop** [ibpsa/project1-boptest#461]
Hello, I'm trying to **run an FMU generated from a Modelica-Spawn model from a pyFMI master code** (in Model Exchange). So far, I managed to run the purely Modelica models (no spawn thermal zones) by extracting the FMU on OpenModelica and then running the simulation with `model.simulate()`. 

When it comes to spawn, my first guess has been to extract the FMU directly from the modelica model that includes the thermal zone, on the hypothesis that it would be enough to call the EnergyPlus dependecies automatically. 

The error I get is:

`
pyfmi.fmi.InvalidBinaryException: The FMU could not be loaded. Error loading the binary. Could not load the FMU binary: cannot find the specified module.`

Moreover, once extracted, the FMU does not contain either the .idf nor the weather files.

- What should my FMU contain? 

- Is spawn supposed to work with two different FMUs (one for Modelica and one for EnergyPlus), so that a single FMU is not enough to run from a pyfmi master code? Or can a single FMU call for the spawn executable to then manage the coupling of Modelica and E+?

Thanks

Details on software and setup:
• OS: Windows 10
• OpenModelica v1.19.0-dev.beta1 (64-bit)
• FMI version: 2.0
• Python 3.8

**Comment by dhblum** [comment]
Hey @davidefop I just want to first mention this isn't directly related to BOPTEST, and more of a question for the Spawn project I think.  But my answer is:

I haven't done any testing of exporting an FMU of a model using Spawn with OpenModelica, so I'm not sure where that capability stands.  But ideally it should work where you can export the model FMU like any other Modelica model, and then to load and simulate with pyfmi you just need to have Spawn installed on your system path.  We've done some testing with compiling a model with Spawn using the Optimica compiler into an FMU and this seems to be able to simulate with pyfmi.

@kbenne Any thoughts on OpenModelica and Spawn?

**Comment by davidefop** [comment]
Sorry for opening the issue on the wrong project. Thanks for replying nonetheless; perhaps the discussion could be closed and continued on an issue I opend on the Buildings library project:

https://github.com/lbl-srg/modelica-buildings/issues/3064

if you deem it more suited.
