### ISSUE TITLE
Service: Admin APIs need to be documented

### ISSUE THREAD

**Issue by kbenne** [ibpsa/project1-boptest#485]
The APIs to add/remove testcases are partitioned off in a separate router for BOPTEST-Service https://github.com/ibpsa/project1-boptest/blob/boptest-service/web/server/src/routes/boptest-admin.js

These APIs need to have tests added and to be documented.

**Comment by dhblum** [comment]
Closing and deferring to https://github.com/NREL/boptest-service/issues/16 and https://github.com/NREL/boptest-service/issues/20.
