### ISSUE TITLE
Update htmlIO python script

### ISSUE THREAD

**Issue by EttoreZ** [ibpsa/project1-boptest#487]
This issue is to update the API calls in the script `get_html_IO.py`. The script is currently not running because the calls are written as:
` ... `
` inputs = requests.get('{0}/inputs'.format(url)).json() `
`...`
 `measurements = requests.get('{0}/measurements'.format(url)).json()`
And so the ['payload'] key selection is missing. The proposed modified code is:
` ... `
` inputs = requests.get('{0}/inputs'.format(url)).json()['payload'] `
`...`
 `measurements = requests.get('{0}/measurements'.format(url)).json()['payload']`

The branch [issue487_update_gethtmlIO](https://github.com/EttoreZ/project1-boptest/tree/issue487_update_gethtmlIO) on my fork is ready for a pull request

**Comment by dhblum** [comment]
Thanks @EttoreZ.  Please make a PR to https://github.com/ibpsa/project1-boptest/tree/issue487_update_gethtmlIO.

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/492.
