### ISSUE TITLE
Update two zone hydrone model documentation

### ISSUE THREAD

**Issue by EttoreZ** [ibpsa/project1-boptest#496]
As per title this issue is to update the documentation of the two zone hydronic model referencing the newly published [paper](https://www.tandfonline.com/doi/full/10.1080/19401493.2022.2120631). @dhblum can you create a branch so I can make a pull request?

**Comment by dhblum** [comment]
Created here: https://github.com/ibpsa/project1-boptest/tree/issue496_twoZoneDocUpdate.

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/498.
