### ISSUE TITLE
Add missing weather variable twozone_apartment_hydronic

### ISSUE THREAD

**Issue by EttoreZ** [ibpsa/project1-boptest#499]
This issues is to address the missing variable `HGloHor` in the test case resource file [weather.csv](https://github.com/ibpsa/project1-boptest/tree/master/testcases/twozone_apartment_hydronic/models/Resources/weather.csv).  [generate_data.py](https://github.com/ibpsa/project1-boptest/blob/master/testcases/twozone_apartment_hydronic/models/generate_data.py) also needs to be updated at line 141 to include `HGloHor` among the generated variables for `weather.csv`. 
@dhblum could you create a branch issue499_addmissingHGloHortwozoneweather, so I can make the pull request

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/506.
