### ISSUE TITLE
Add check and warning in data_manager.py for all weather variables

### ISSUE THREAD

**Issue by EttoreZ** [ibpsa/project1-boptest#500]
This issue is to add a warning message in [`data/data_manager.py` ](https://github.com/ibpsa/project1-boptest/blob/master/data/data_manager.py), that checks wether all the common weather variables, taken from [`data/categories.json`](https://github.com/ibpsa/project1-boptest/blob/master/data/categories.json), are included in the `testcase/Resources/weather.csv`. In the case `weather.csv` does not include all variables, a warning will be displayed to the user.

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/645.
