### ISSUE TITLE
testcase: multizone_office_simple_hydronic steerability

### ISSUE THREAD

**Issue by bmerema** [ibpsa/project1-boptest#501]
At DeltaQ we identified some issues with the BOPTEST building (multizone_office_simple_hydronic) regarding the overriding of the control to set the supply temperatures for the heating circuits and air temperature. For example, if we write a value of 320K to 'bms_oveTSupEmiHeaNz_u', we see it is not respected and the temperature remains at 330K even after advancing for a number of steps. Similar behaviour is noticed for setting the air temperature supply. Therefore, at DeltaQ we are currently trying to resolve these issues regarding the steerability of this BOPTEST model.

**Comment by dhblum** [comment]
Thank you for the report.  Are you testing over a particular starting and ending time?

**Comment by bmerema** [comment]
Currently we are testing a heating MPC only. Therefore, I tested from time 0 with two weeks of warmup and then the start of the control where I control the emission system and the AHU.

**Comment by dhblum** [comment]
I did a little simulation testing.  At time=0 and at time=15 days it seems to be the weekend when the system is off, or more specifically, there is no airflow through the AHU nor water flow through the fan coil.  Hence, the temperature of those supply streams won't be controllable.  See the plot below.  Does this help?  Is the overwrite responsive when you do so during a time there is air and water flows through the systems?
![Result_day15](https://user-images.githubusercontent.com/19480999/201692573-7d5be863-1e79-4411-a645-2f31d3c73d69.png)

**Comment by bmerema** [comment]
Sorry, maybe I was not clear. I started from that time onwards with an MPC where I override the control that's existing using the BOPTEST framework where I control the North Zone. So I allow water and airflow by activating bms_ovePrfAhuSupNz_u and bms_ovePrfEmiHeaNz_u and than also write to the supply temperature of these two circuits.  From the first monday afterwards I sent lower supply water temperatures at start for the emission system. For example 315 K, however it stays at 330K even after advancing the control for multiple steps. 
I actually notice these problems during both times (on and off time). I already noticed that the boiler requires both prfEmi and prfAhuHea to be on as well as that the Tsup for the boiler is determined by the maximum of the four heating circuits.

**Comment by bmerema** [comment]
In the meantime I wanted to compile the model and build the docker. The compilation as FMU in OM works fine. However, I get the following error as shown below. In addition, the compilation with OCT does not seem to work for me even though I used the same checkouts as mentioned by Iago (error >Failed to compile the C code: Compilation of generated C code failed.). Do you have any suggestions on how to solve these kind of issues?
 
TESTCASE=multizone_office_simple_hydronic docker-compose up
Starting iagoproject1-boptest_boptest_1 ... done
Attaching to iagoproject1-boptest_boptest_1
boptest_1  | Traceback (most recent call last):
boptest_1  |   File "restapi.py", line 63, in <module>
boptest_1  |     case = TestCase()
boptest_1  |   File "/home/developer/testcase.py", line 57, in __init__
boptest_1  |     self.fmu = load_fmu(self.fmupath)
boptest_1  |   File "src/pyfmi/fmi.pyx", line 8084, in pyfmi.fmi.load_fmu
boptest_1  |   File "src/pyfmi/fmi.pyx", line 7135, in pyfmi.fmi.FMUModelME2.__init__
boptest_1  |   File "src/pyfmi/fmi.pyx", line 3848, in pyfmi.fmi.FMUModelBase2.__init__
boptest_1  | pyfmi.fmi.FMUException: Error loading the binary. Could not load the FMU binary: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/JModelica.org/jm_tmpwuVgmf/binaries/linux64/wrapped.so)

**Comment by dhblum** [comment]
Regarding the error you show, did you compile with OM on Windows or Linux?  Linux compilation is required since the docker creates a Linux simulation environment.  Regarding compilation with OCT, I have not done any testing with that so can't help at the moment.

**Comment by bmerema** [comment]
Its compiled with OM on Linux. I tried several of the platform options that are available in OM but all result in the same error.

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________

**Comment by dhblum** [comment]
Can you report the versions of OM and Linux you are using?

**Comment by bmerema** [comment]
Linux 20.1 (ulyssa) and OpenModelica 1.21.0~dev-14-gdf98762

**Comment by dhblum** [comment]
Hm, could the FMU binary error be because the BOPTEST docker environment uses Ubuntu 18 and you've compiled the FMU on Ulyssa?

**Comment by dhblum** [comment]
UPDATE: I compiled the wrapped.mo of this model into an FMU using OpenModelica 1.21.0~dev-9-g8912034 on Ubuntu 18.  I then copied the FMU into a running BOPTEST container and did a simple command to simulate the FMU.  Didn't get the FMU binary error, though did get an initialization error, which is a separate issue I suppose.  So, seems like it could be the Linux version of compilation that's causing your FMU binary error.

**Comment by dhblum** [comment]
@bmerema It seems from our discussion in the IBPSA meeting that the issue of steerability in the emulator has been solved.  Can I close this issue and we continue addressing problems related to compiling and simulating of the emulator in https://github.com/ibpsa/project1-boptest/issues/465, or create new specific issues to address those problems?

**Comment by bmerema** [comment]
@dhblum indeed the issue has been solved i will push my changes soon to the issue #465. I think the issues concerning the compiling and simulating can be indeed addressed in #465 as it would be good to compile and simulate the model in OM.
