### ISSUE TITLE
Update/Add introductory tutorial

### ISSUE THREAD

**Issue by dhblum** [ibpsa/project1-boptest#507]
This issue is to update the introductory tutorial at https://github.com/ibpsa/project1-boptest/tree/master/docs/workshops/BS21Workshop_20210831 for v0.3.0 and also consider creating a testing environment to maintain that tutorial through version increments.

Related issue https://github.com/NREL/boptest-service/issues/16.

@jmythms has an updated version to PR and serve as a starting point for any additional edits to text and testing framework.

@JavierArroyoBastida, @kbenne.

**Comment by JavierArroyoBastida** [comment]
Loving this initiative. Thanks for the update!

**Comment by jmythms** [comment]
@dhblum May I get push access to upload the updated notebook?

**Comment by dhblum** [comment]
@jmythms working on it.  When you do, please create a development branch as ``issue507_updIntTut`` and make a PR.

**Comment by JavierArroyoBastida** [comment]
I suggest waiting for https://github.com/ibpsa/project1-boptest/pull/508 to be merged since that will also require some updates on the tutorial.

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/510.
