### ISSUE TITLE
help,New person discussion

### ISSUE THREAD

**Issue by rainbownmm** [ibpsa/project1-boptest#512]
My friend, I need some help with boptest. Is there a more detailed local deployment tutorial? Why do I visit 5000/measurements after my local deployment? All the returned values are null. When I visit 5000/forecast, he returns "The method is not allowed for the requested URL." I don't know what causes this result. Please help me. Thank you

**Comment by Puzzledyy** [comment]
![1671070367285](https://user-images.githubusercontent.com/120607490/207756254-7c2deb8b-1bdb-45cd-8c97-a1b5f38a214b.png)

**Comment by dhblum** [comment]
@Puzzledyy I'm sorry I'm not clear on your question.  Based on your second post, it seems /measurements is working correctly, as it returns the list of available measurement points and meta data.  Regarding the use of /forecast, in the latest official version of BOPTEST 0.3.0, the /forecast API is a GET request which should return the forecast data for the test case you've deployed.  If you are using the latest master branch, this has changed according to the [release notes](https://github.com/ibpsa/project1-boptest/blob/master/releasenotes.md), where the API request is a PUT with required parameters to be given (see [here](https://github.com/ibpsa/project1-boptest#test-case-restful-api)).
