### ISSUE TITLE
/version endpoint

### ISSUE THREAD

**Issue by epaulson** [ibpsa/project1-boptest#516]
Also low-priority, but as the tree is in-between releases, could the /version endpoint return something like 0.3.0-dev (or 0.4.0-dev) instead of 0.x.x?

**Comment by dhblum** [comment]
Yes, I agree.  Thank you for the suggestion.  I suggest ``<next planned version>-dev``.

**Comment by dhblum** [comment]
Or, maybe it's better to do ``<most recent version>-dev``, since the next release version may not be certain based on backwards compatibility and major vs. minor version number increments.

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/517.
