### ISSUE TITLE
SyntaxError: JSON.parse: unexpected character at line 1 column 268 of the JSON data for testcase2

### ISSUE THREAD

**Issue by kefeimo** [ibpsa/project1-boptest#540]
### Description (How to reproduce)

For
* version 0.4.0-dev
* TESTCASE=testcase2

When using `curl http://127.0.0.1:5000/kpi`,
![image](https://github.com/ibpsa/project1-boptest/assets/28743873/e7a695d6-3e9f-4f56-adad-99d06e127b05)

it returns raw json
```json
{"message":"Queried KPIs successfully.","payload":{"cost_tot":0.005221328521720328,"emis_tot":0.013053321304300819,"ener_tot":0.026106642608601637,"idis_tot":0.0,"pdih_tot":null,"pele_tot":0.037526602248043876,"pgas_tot":null,"tdis_tot":2.0119814359592807,"time_rat":NaN},"status":200}
```
Note the return is not a valid json due to `"time_rat":NaN`

### Expected Result
Return valid Json.

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/543.
