### ISSUE TITLE
BOPTEST no longer includes `forecastParameters` in the results payload to dashboard

### ISSUE THREAD

**Issue by kbenne** [ibpsa/project1-boptest#548]
As a result the dashboard will not accept BOPTEST results submnissions. Now that forecastParameters are specific to each variable, we're going to need to update the dashboard to accomodate this change.

**Comment by dhblum** [comment]
I think what was done in https://github.com/NREL/boptest-service/commit/717d2a4267401f07be64277a44a40aaedd210d01 for a temporary fix in Service will need to be done in BOPTEST core as well until the dashboard is updated.

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/549.
