### ISSUE TITLE
aws 403 forbidden

### ISSUE THREAD

**Issue by P11GH** [ibpsa/project1-boptest#551]
Hi, I ran the command "TESTCASE=testcase1 docker-compose up", but got the error of " HTTP request sent, awaiting response... 403 Forbidden" for spawn, as shown in the screen shot below. What would be the cause of it? Could you help to solve it?
<img width="868" alt="image" src="https://github.com/ibpsa/project1-boptest/assets/50893243/5546728e-43c0-45d8-bcc7-b1a1eed63942">
I also ran several other testcases, but got the same error.

**Comment by dhblum** [comment]
Thank you for reporting.  @kbenne I actually see this error too when I try a fresh BOPTEST image build on an Ubuntu 20 VM.  Do you know why Spawn is not accessible from the provided link anymore?

**Comment by kbenne** [comment]
Sorry about this. It should be fixed now.

**Comment by dhblum** [comment]
Thanks @kbenne!  Confirmed this is resolved.
