### ISSUE TITLE
Materials for BS2023 workshop

### ISSUE THREAD

**Issue by JavierArroyoBastida** [ibpsa/project1-boptest#552]
This is to generate the necessary materials for the BS2023 workshop planned for September 4-6, 2023. The idea is to use a similar format to the workshop held for BS2021. However, the workshop has a maximum duration of 1h30m, compared to the 3h30m that we used during BS2021, and I'd like to include a final part on BOPTEST-Gym. Therefore, we probably want to skip parts 3 and 4 of the original workshop:
- Part 3: (Presentation) Example Development and Evaluation of an MPC Controller
- Part 4: (Exercise) Improving Controller Performance and Reporting Results

I'll come up with a suggestion by tomorrow.

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/573.
