### ISSUE TITLE
Forecast horizon = 0

### ISSUE THREAD

**Issue by JavierArroyoBastida** [ibpsa/project1-boptest#554]
In [this line](https://github.com/ibpsa/project1-boptest/blob/a9aaec3bb44bc9bd362f3d3002e6d940584c708e/testcase.py#L862) we prevent from forecast horizons of 0. Fundamentally, that makes sense. However, the only way for a user to get to know current boundary condition data other than weather is by using the forecaster with a prediction horizon of 0. In the case of weather data, we have the weather station block, but there are others like pricing or setpoints that couldn't be retrieved for the current time otherwise. A use case can be e.g. a PI controller that reacts to deviations from a setpoint, or a reinforcement learning agent that includes current setpoints and pricing in its observation space. I therefore suggest to change the `<=` of that line to `<`.

**Comment by dhblum** [comment]
I agree that there is need for the use cases you mention and this seems like a simple implementation that uses existing API.  Care to make a PR?

**Comment by JavierArroyoBastida** [comment]
Sure! sent it https://github.com/ibpsa/project1-boptest/pull/558.

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/559.
