### ISSUE TITLE
controller files for more test cases

### ISSUE THREAD

**Issue by P11GH** [ibpsa/project1-boptest#556]
Will the controllers for all test cases in the testcases folder be available? I notice that there is no corresponding controller files in the examples folder for some cases in the testcases folder.

**Comment by dhblum** [comment]
All test cases come with embedded controllers.  The controllers that are available for testcases1-3 are example test controllers written for those test cases which demonstrate usage of the BOPTEST API to implement a controller of your own for any of the test cases.  We do not currently have scope to implement example test controllers for all test cases.

**Comment by P11GH** [comment]
> All test cases come with embedded baseline controllers. The controllers that are available for testcases1-3 are example test controllers written for those test cases which demonstrate usage of the BOPTEST API to implement a controller of your own for any of the test cases. We do not currently have scope to implement example test controllers for all test cases.

Got it. Thanks
