### ISSUE TITLE
Enumeration KPI Tag

### ISSUE THREAD

**Issue by dhblum** [ibpsa/project1-boptest#57]
The tagging of signals for KPI calculation with an enumeration parameter instead of string parameter requires changes to the parser in how it identifies the tags.

**Comment by JavierArroyoBastida** [comment]
@dhblum I think you are referring to a change to the parser that has already implemented in https://github.com/JavierArroyoBastida/project1-boptest/commit/6dd6518e47f0d7898922a7bfbf2e5c0951d12129 
isn't it?

**Comment by dhblum** [comment]
@JavierArroyoBastida Yes that's right.  My mistake, did not see that implementation.  Yours is cleaner than my proposed as it does not require duplication of the types in Python.  I will close this issue and delete the associated branch.
