### ISSUE TITLE
Materials for RLEM2023 workshop

### ISSUE THREAD

**Issue by JavierArroyoBastida** [ibpsa/project1-boptest#585]
This is to generate the necessary materials for the BS2023 workshop planned for November 12, 2023. The idea is to use a similar format to the workshop held for BS2021 since we have the same time (3.5 hours) but slightly change the program to include a part on BOPTEST-Gym. The agenda can be found in [this link](https://rlem-workshop.net/talks/tutorial/Tutorial%202): 

**Presentation: BOPTEST motivation, goals, and approach (15m)**

**Exercise 1: Introductory hands-on tutorial on the software (1h15m)**
- Introduce the Google Colab environment
- Selecting a test case
- Exploring the API
- Develop a feedback controller for the test case
- Add forecast to your feedback controller
- Reporting results

**Coffee break (10m)**

**Presentation 2: An example MPC controller in BOPTEST (10m)**

**Exercise 2: Learning BOPTEST-Gym, the Gym interface of BOPTEST (20m)**

**Exercise 3: Timed common exercise (1h10m)**
- Introduce exercise goals: optimize the controller from Exercise 1
- Complete exercise, submit results, produce presentation reports
- Volunteer participants present findings and group discussion

**Wrap-Up and follow-up explanation (10m)**

To-dos:
- [x] Sort tutorial to accommodate to new agenda. 
- [x] Update BOPTEST-Gym to use Service 0.5.0.
- [x] Update tutorial to use BOPTEST 0.5.0 and thus `json` instead of `data` in API calls. 
- [x] Update presentations and Google form for participants.

**Comment by JavierArroyoBastida** [comment]
@dhblum @kbenne I've implemented a first working version of the notebook for the workshop [here](https://github.com/JavierArroyoBastida/project1-boptest/blob/issue585_rlem2023/docs/workshops/RlemWorkshop_20231112/Introduction_to_the_BOPTEST_framework.ipynb). Please note it's still using `BOPTEST-Service v0.4.0`. Please let me know whether Service is updated to `v0.5.0` implement the corresponding edits. If we do not update before the workshop we should work out a Google sheet for comparing KPIs in the timed exercise. If we do the update we should explain better in the workshop how the comparison is going to be made. @dhblum any thoughts on that?

The notebook is very similar to the one we used for BS2021 but also includes a small section on BOPTEST-Gym and updates the Follow-up section to announce the ADRENALIN challenge. 

Any input/suggestion is very welcome!

**Comment by dhblum** [comment]
@JavierArroyoBastida Thank you very much for setting this up.  BOPTEST-Service has been updated to support v0.5.0.  So if you hit api.boptest.net, you'll be using the latest version.

**Comment by JavierArroyoBastida** [comment]
@dhblum I've just updated the notebook to use `json` instead of `data` in the API calls. See [here](https://github.com/ibpsa/project1-boptest/commit/e7e88013a1f8d5233851cf66826bde808f19479d). I also indicated we work with BOPTEST version 0.5.0. Note that the notebook could run without the update to `json` in the API call when working with v0.5.0, but I implemented the change anyhow. Seems that the part of BOPTEST-Gym part of the notebook is working as well even though I did not change `data` by `json` in BOPTEST-Gym nor changed it to test against BOPTEST v0.5.0. However, I plan to do so before the workshop and consequently update BOPTEST-Gym to v0.5.0 as well (without any other major update). 

One thing that is still open is how we are going to compare the results of the timed exercise. Do you think we could ask participants to use the `submit` API call and compare the results in the dashboard?

Other than that, we just need to prepare slides for the workshop. I suggest to use almost same [presentations we used for BS2021](https://github.com/ibpsa/project1-boptest/tree/master/docs/workshops/BS21Workshop_20210831/presentations) but changing headers/dates or other adjustments needed, and drop them to [our drive](https://drive.google.com/drive/folders/1h5eJ-WxwvLqjYleoZya-8AOjIuXazIy0?usp=drive_link).

**Comment by dhblum** [comment]
Thanks @JavierArroyoBastida.  I think it's better to use json so thanks for updating.

About results comparison, I'm not sure about the dashboard.  The dashboard expects some updates to be deployed but I don't think @kbenne's gotten to that yet.  We'd have to caveat that the dashboard data may not persist yet at this point so data could still be lost.  And we'd have to add a piece to the tutorial about how to register for the dashboard and use the submit API.  We'd probably instruct to use a tag "RLEM23" or something.  The alternative would be to do what we did last time, create a shared google sheet that participants can log their results, and then we can also plot them etc.

I plan to just use for the intro what I used for BS23 with updated title, and maybe anything else that needs updating.  Dropping them in the drive for now is fine, but eventually we can post to the repo as we've done others.

Are we planning to keep all the materials on your fork until after the workshop when we merge back to origin?  Just thinking about what links we give out to access the colab.

**Comment by kbenne** [comment]
I'm sorry, but the 0.5.0 update of the service has been a bit bumpy so I think it is going to be a struggle to have dashboard updates.

On a different note, @JavierArroyoBastida please keep me updated on how your testing and preparation goes while using the 0.5.0 version. We've had some reports about timeouts, which have me a bit concerned.

**Comment by JavierArroyoBastida** [comment]
Then I suggest using a shared google sheet as in the past. I've created an empty copy of previous versions in [our drive](https://drive.google.com/drive/folders/1h5eJ-WxwvLqjYleoZya-8AOjIuXazIy0?usp=drive_link), that should always work. 
I suggest keeping the materials in my fork until after the workshop. That allows more flexibility for quick edits, and we can merge a more stable version once the workshop is done. 
@kbenne so far Service has always worked fine. I've been able to interact with it without any issue. I'll let you know otherwise.

**Comment by dhblum** [comment]
@JavierArroyoBastida All sounds good.  Glad you haven't seen Service issues too.

**Comment by dhblum** [comment]
@JavierArroyoBastida I've uploaded the intro presentation to the drive.

**Comment by JavierArroyoBastida** [comment]
I see. Thanks @dhblum! I'm upgrading BOPTEST-Gym to use Service 0.5.0 [here](https://github.com/ibpsa/project1-boptest-gym/pull/136). It'll be ready by today or tomorrow the latest, but our RLEM tutorial notebook runs independently of these edits since it's little what we go into BOPTEST-Gym.

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/586.
