### ISSUE TITLE
Update location of jmodelica docker image

### ISSUE THREAD

**Issue by dhblum** [ibpsa/project1-boptest#590]
The JModelica Docker image off which ``testing/Dockerfile`` builds has moved to https://hub.docker.com/repository/docker/lbnlblum/ubuntu-1804_jmodelica_trunk/general.  This issue is to update the location accordingly.  It will be a few weeks/months until the old location is removed.

**Comment by dhblum** [comment]
@EttoreZ Can you address this and make a PR for it?

**Comment by EttoreZ** [comment]
Sure @dhblum no problem.

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/593.
