### ISSUE TITLE
Add REST IO Block to Model

### ISSUE THREAD

**Issue by dhblum** [ibpsa/project1-boptest#6]
This issue is to add the IO block to the test case model to demonstrate its use.  See also https://github.com/ibpsa/project1-boptest/pull/5.

**Comment by dhblum** [comment]
@SenHuang19 I run into an issue trying to use the Modelica model in your pull request with the latest version of the Modelica IBPSA Library branch https://github.com/ibpsa/modelica-ibpsa/issues/926.  It seems the name of the io block has changed from Read_Real perhaps to Sampler_Real.  Can you push the most up to date version of your model to your pull request?

**Comment by SenHuang19** [comment]
@dhblum let me double check and I will create a new pull request which contains the test case with PI as well

**Comment by dhblum** [comment]
I have implemented the io block in the single RC model for actuator and setpoint control, as well as sensing of a few measurement points.  However, I run into issues with the transmission of actuator signals, where what appears in the model is multiplied by 100. 

Relevant code: 
testcase/models/SimpleRC_Input.mo 
testcase/interface/server.py

To reproduce:
In terminal: $ python server.py
Run .mo model in Dymola and check acs_actuator.y[1]

<img width="928" alt="rc io block error" src="https://user-images.githubusercontent.com/19480999/44303355-cd4e1800-a2f3-11e8-8ade-e056563c2c47.png">

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/18 via https://github.com/ibpsa/project1-boptest/issues/15.
