### ISSUE TITLE
SSLCertVerificationError for Boptest API (https://api.boptest.net)

### ISSUE THREAD

**Issue by AlinaCartus** [ibpsa/project1-boptest#603]
No matter what testcase I choose, when I try to reach the boptest-api like that (using colab):

![error](https://github.com/ibpsa/project1-boptest/assets/92786532/12a1ae0a-8182-4f63-8ed8-620cc431ba8d)

there is the error "SSLCertVerificationError" with the following consequential errors: "SSLError" and "MaxRetryError". For details check .txt file. 

[error.txt](https://github.com/ibpsa/project1-boptest/files/13700460/error.txt)

I hope, I am not missing something obvious and look forward to your support! Thank you in advance

**Comment by dhblum** [comment]
@AlinaCartus Thank you for reporting!  @kbenne and I will look into this and address as soon as we can.

**Comment by kbenne** [comment]
Certificates are renewed now.

**Comment by dhblum** [comment]
Thank you @kbenne.  I confirm https://api.boptest.net/version returns ``{"status":200,"message":"Queried the version number successfully.","payload":{"version":"0.5.0","service-version":"0.3.0"}}``.
