### ISSUE TITLE
Low setpoint temp in docs for multizone_office_simple_air

### ISSUE THREAD

**Issue by dhblum** [ibpsa/project1-boptest#605]
12 C for TZonCooSet as shown in documentation for ``multizone_office_simple_air`` looks low.  This issue will double check the model to see if it is just a typo or not.

![Screenshot 2024-01-11 195233](https://github.com/ibpsa/project1-boptest/assets/19480999/a8d7b910-d3ca-4ecd-9fbf-db11dab517e9)

**Comment by dhblum** [comment]
@EttoreZ Can you look into this and check it is indeed a typo?  If so, can you make a PR with a correction?

**Comment by EttoreZ** [comment]
@dhblum I checked that it is just a typo and corrected it in the following PR https://github.com/ibpsa/project1-boptest/pull/615.
