### ISSUE TITLE
Store scenario results when completed

### ISSUE THREAD

**Issue by haraldwalnum** [ibpsa/project1-boptest#626]
This issue is to implement a function that stores the scenario results KPIs++ and time series measurements in the simulation directory, so that this can be restored later with the "testi_id" if ran with service.

**Comment by HWalnum** [comment]
@dhblum and @kbenne , we can continue the discussion here.
We should decide what we should store, and naming.
Actually I don't see the need to store results from different scenarios with different names, but rather just overwrite existing stored results.

The need for downloading results from the database is a special need (so far the only use case is competitions?). 
If users need to store results from multiple runs, they should rather use the API to request results and kpis, and store themselves.

Also when results from multiple runs from the same testcase is needed, why not require that the user reloads the testcase and get a new "test_id". I don't think it is much overhead with this?

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/632.
