### ISSUE TITLE
have 404 error for spawn when trying to build a test case using docker

### ISSUE THREAD

**Issue by Fanccccc** [ibpsa/project1-boptest#656]
hi, I ran the command **TESTCASE=bestest_hydronic_heat_pump docker-compose up**, but met the following error

Connecting to spawn.s3.amazonaws.com (spawn.s3.amazonaws.com)|52.216.162.3|:443... connected.
HTTP request sent, awaiting response... 404 Not Found

It seems that I cannot run wget https://spawn.s3.amazonaws.com/custom/Spawn-$SPAWN_VERSION-Linux.tar.gz in Dockerfile
![1](https://github.com/user-attachments/assets/1243944a-ca5e-43d3-9d13-a8617d9b6553)

Could you help me solve this?

**Comment by Norah135** [comment]
I am facing the same issue if you find a solution for it can you please share it with us

**Comment by dhblum** [comment]
Thanks for reporting, I can replicate the error.  I need to check with the Spawn developers on this one.  Will get back asap.

**Comment by kbenne** [comment]
Sorry everyone. This should be fixed now. 

`wget https://spawn.s3.amazonaws.com/custom/Spawn-0.3.0-8d93151657-Linux.tar.gz`

**Comment by dhblum** [comment]
Thank you @kbenne!  I confirmed download with wget works.  Closing this as resolved.
