### ISSUE TITLE
import name 'trapz' from 'scipy.integrate'

### ISSUE THREAD

**Issue by Norah135** [ibpsa/project1-boptest#657]
I am having an issue deploying the test case in Docker using `TESTCASE=test_case docker-compose up`. Here is an image that describes the problem(cannot import name 'trapz' from 'scipy.integrate').

<img width="875" alt="Screenshot 2024-07-16 at 9 54 24 AM" src="https://github.com/user-attachments/assets/8a127f3f-ad11-4315-bf16-a5e3d3309065">
 Do you have any suggestions on how I can fix it?"

**Comment by dhblum** [comment]
Hey @Norah135, I just ran ``$ TESTCASE=bestest_air docker-compose up`` using the master branch and on Ubuntu 18 running Docker version 24.0.2.  Can you be more specific about the version of BOPTEST, Docker, and platform/OS you are deploying on, and whether you made any changes to the Dockerfile or otherwise?  The version of scipy used within the test case container should be consistent across image builds.

**Comment by Norah135** [comment]
I really appreciate your quick response. I tried using both an Apple and a Windows device running Docker version 26.1.4, but I'm facing the same issues on both. I downloaded the latest version (6) of BOPTEST from the website and haven't made any changes to the Docker file.

**Comment by Norah135** [comment]
@dhblum  I wanted to ask if you can help me use the BOPTEST API without running it on Docker. I'm facing issues with Docker. I found an example on Colab, but I'm a little confused about how to connect this example with a simple control algorithm to understand how the system works. I am looking for examples similar to what we have in the GitHub repository (the test case and the interface file). Sorry to bother you, but I am new to this field and using the software. I really appreciate any guidance and help from you.

**Comment by dhblum** [comment]
Ok I've reproduced your error on a MacBook (Intel).  This needs to be looked into.  I don't know why Docker would be trying to, potentially, use a different version of scipy.

If you open the colab of the first tutorial listed [here](https://ibpsa.github.io/project1-boptest/training/index.html), it will take you through using the BOPTEST public web service to test a simple controller.  Using the web service, you don't need to build BOPTEST locally. 

Hopefully that's helpful for you to get started and thanks again for reporting the issue.

**Comment by dhblum** [comment]
Ok specifying the version of scipy to 1.13.0 in this line fixes this issue.  Using ``pip install`` is the preferred approach over ``conda install`` I think as it seems to solve environments and install all the packages faster.  

I could PR this fix.  But any ideas from anyone why two different scipy versions would be installed in a Docker container depending on Platform under which Docker is operating?  @kbenne @javiarrobas @EttoreZ? 

This might be related to what I'm observing in https://github.com/ibpsa/project1-boptest/issues/655.

**Comment by EttoreZ** [comment]
Hey @dhblum maybe this [link](https://stackoverflow.com/questions/49106336/docker-and-conda-differences-when-building-the-same-container-on-mac-and-on-ubu)? It seems that depending on the situation, Docker may not download the latest version of the image.

**Comment by Jaap-Neven** [comment]
Hi @dhblum, @EttoreZ and @Norah135,
I have encountered exactly the same issue using the most recent version of boptest (master branch) and v4.32.0 of docker desktop on Windows 10 OS. A couple of weeks ago, the testcases ran fine for me, so I tested the deployment with the previous version of docker desktop (v4.31.1) and now if works fine. So it should have something to do with the recent [docker desktop release notes](https://docs.docker.com/desktop/release-notes/).

Hope this was helpful!

**Comment by Norah135** [comment]
Hi@dhblum  
Thank you for sharing the Colab link. It was very helpful. I wanted to ask if it is possible to create my own test case for BOPTEST instead of using the predefined cases listed on the BOPTEST website.

**Comment by dhblum** [comment]
Thanks @Jaap-Neven your insight is helpful.  In any case, I will specify the version of scipy for now to fix this issue.  Looking at removing reliance on scipy in the first place will be another issue.  Note this will be included in this existing PR https://github.com/ibpsa/project1-boptest/pull/659, and I'll close this issue when PR is merged.

@Norah135 Here is documentation for how test cases are designed: https://ibpsa.github.io/project1-boptest/docs-design/testcasedev.html.  Additionally, here is a basic tutorial for putting together a test case: https://github.com/ibpsa/project1-boptest/blob/master/docs/tutorials/tutorial1_developer/BOPTEST_Tutorial1_developer_20230416.pdf.

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/659.
