### ISSUE TITLE
Change position of living room setpoint overwrite block for Multizone Residential Hydronic testcase

### ISSUE THREAD

**Issue by EttoreZ** [ibpsa/project1-boptest#660]
This issue is to address a problem with the overwrite input to the living room heating setpoint. This setpoint is used to control the boiler for the whole apartment and if overwritten ,`oveTSetPum`, only the pump signal is updated, while the old setpoint is used to control the boiler as highlighted in the figure below: 
<img width="598" alt="image" src="https://github.com/user-attachments/assets/d34b555f-759c-4395-8386-a9e0c13dbed3">
So the connections within the test case model will be updated such that `oveTSetPum` will become `oveTSetPumBoi` and overwrite both the pump and boiler living room setpoints.

**Comment by dhblum** [comment]
CLosed by https://github.com/ibpsa/project1-boptest/pull/667.
