### ISSUE TITLE
Julia controller tests reference results file not in repo

### ISSUE THREAD

**Issue by dhblum** [ibpsa/project1-boptest#67]
The julia controller unittests reference results files generated by the Julia controller example that are not included in the repo.  Instead, they should reference the results in the reference directory of the unittests.

**Comment by SenHuang19** [comment]
are you suggesting that the julia output should be put into the testing folder?

**Comment by dhblum** [comment]
No, this is a bug that I have the unit tests pointing to results that are not in the unit test reference results directory.  I plan to fix very soon.

**Comment by dhblum** [comment]
Actually, on second look, I am closing this issue, as the unit tests first run the julia controller to produce test results, then pull the test result file from the example and compare it to reference results stored in the testing directory.  This is how it should be.
