### ISSUE TITLE
Directory issue when testing KPIs using test_kpis.py

### ISSUE THREAD

**Issue by Jaap-Neven** [ibpsa/project1-boptest#672]
While looking at #639, I wanted to run [test_kpis.py](https://github.com/ibpsa/project1-boptest/blob/7deb826ce27b528a1bf0721fbb8a1424086ebc4d/testing/test_kpis.py) in order to test the new kpi implementation. This script uses results from testcase2 and testcase3 to obtain the kpi values.

Running all the tests resulted in the error below, where the specified directory can not be found. This snapshot clarifies it crashes for testcase2, but the same error shows for testcase3. 

![image](https://github.com/user-attachments/assets/b48c444b-e242-4280-a869-9068adfcac34)

Is running test_kpis.py directly the correct way to see if the defined kpis are behaving correctly, or is there another dedicated file doing this without errors? In case of the former, I'll have a look at how to refer to the correct directory.

**Comment by dhblum** [comment]
@Jaap-Neven Thanks for reporting.  The best way to run the tests is outlined in /testing/README.md.  There you can find instructions for the kpi test, which actually is run within a docker container.  Admittedly, this README and those tests were written a while ago and could probably use some updating to make running code easier for dubugging and new users, and potentially make the README more accurate if there have been changes not reflected there in terms of instructions.

**Comment by Jaap-Neven** [comment]
Hi @dhblum, thanks for the response. This makes more sense and the ReadMe file here is still viable imo.

**Comment by dhblum** [comment]
👍
