### ISSUE TITLE
Change Test cases library dependencies

### ISSUE THREAD

**Issue by EttoreZ** [ibpsa/project1-boptest#680]
Test cases `Bestest hydronic` and `Bestest hydronic heat pump` are extensions of `IDEAS.Examples.IBPSA.SingleZoneResidentialHydronic` and `IDEAS.Examples.IBPSA.SingleZoneResidentialHydronicHeatPump`. This makes it hard to implement changes to those model since it requires directly modifying IDEAS library, for example:

- Re parametrization  of the model
- Additional of semantic annotations to models within test case model
- Update test case model to Modelica 4.0 and have it run with OpenModelica

For this reasons this issue suggests to modify the current BOTPEST Modelica Test case implementation by duplicating the models instead of extending them.

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/681.
