### ISSUE TITLE
Migrate logging and timeout changes from NREL/boptest-service

### ISSUE THREAD

**Issue by kbenne** [ibpsa/project1-boptest#684]
A handful of changes related to logging and message timeout were made in the NREL/boptest-service repo. These were changes made in support of the Adrenalin compeition. The purpose of this issue is to merge those changes into this repository.

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/commit/891f99baafc471fc1520e2490d5085e481cf4d9f.
