### ISSUE TITLE
Custom KPI clutter in examples

### ISSUE THREAD

**Issue by Jaap-Neven** [ibpsa/project1-boptest#692]
# Problem description
When defining custom KPIs in one of the examples (using [interface.py](https://github.com/ibpsa/project1-boptest/blob/691da40dfa53f8d9a43f8d008b0b9b568c28e3ee/examples/python/interface.py)), it prints each custom KPI every step of the loop, which causes clutter such that important test case information is lost in the runtime environment. Example of only part of the print output: 
![image](https://github.com/user-attachments/assets/755c66e6-0ffe-40c7-a3db-58c6c75051ea)

# Proposed fix
At the end of the code, print the custom KPIs as a pandas dataframe, as shown in the figure below: 
![image](https://github.com/user-attachments/assets/e0aa7d0e-6bbe-42d7-9653-caf7accd6a11)

Can implement together with #688

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/697.
