### ISSUE TITLE
Customized KPI Calculation

### ISSUE THREAD

**Issue by dhblum** [ibpsa/project1-boptest#83]
This issue is to integrate the customized KPI calculation.

To Do:

- [x] Merge from Sen's development
- [x] More documentation in docstrings and readme.
- [x] Delineate required and optional keys in kpi config.
- [x] Make ``data_point_num`` not required for be specified for all kpis.

**Comment by SenHuang19** [comment]
I accidentally commit to the issue83_customKPI branch directly

**Comment by dhblum** [comment]
No problem, this works too!

**Comment by dhblum** [comment]
I've merged the most recent master to the branch.

**Comment by dhblum** [comment]
Hey @SenHuang19 , here are comments I have:

- [ ] More documentation could be added, particularly as docstrings for method and class descriptions and a guide (in the form of a ``readme``) for potential users who want to adopt the capability as you demonstrated.  
- [ ] It seems that the kpi configuration file has a number of keys that are required, and some that are not.  I suggest somehow delineating between which are required and which are not.
- [ ] I don't think data_point_num needs to be in all KPI configuration files, but instead could be handled within the KPI calculation classes themselves, since they are classes and have memory.  Removing this from the config or making it optional simplifies the interface I think.

**Comment by SenHuang19** [comment]
Update the pull request #95
Specifically, I made the customized KPI compatible with both testcase 1 and 2

**Comment by dhblum** [comment]
I merged https://github.com/ibpsa/project1-boptest/pull/95 and opened https://github.com/ibpsa/project1-boptest/pull/143 for merge to master.

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/143.
