### ISSUE TITLE
Move design and requirements document from google doc

### ISSUE THREAD

**Issue by dhblum** [ibpsa/project1-boptest#97]
This issue is to move the design and requirements document from a google doc to rst-based documentation in this repository.

**Comment by dhblum** [comment]
@yanchenpnnl To work on update for KPIs and associated Appendix.

**Comment by dhblum** [comment]
@yanchenpnnl Development is on branch https://github.com/ibpsa/project1-boptest/tree/issue97_docDesign.

**Comment by dhblum** [comment]
The documentation will be moved as written in google docs today (12/24/2019).  Additional necessary updates will be made with future issues.

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/140.

**Comment by SenHuang19** [comment]
I suggest we to create a github wiki for showing this document

**Comment by dhblum** [comment]
Can we easily manage the wiki using rst files?
